### ISSUE TITLE
Exchange - panics when context=nil

### ISSUE THREAD

**Issue by porjo** [golang/oauth2#100]
Calling `Config.Exchange()` with `ctx` set to nil results in panic. This wasn't a problem prior to [this commit](https://github.com/golang/oauth2/commit/96e89befdc0f88d5868b297eb0e0727ce6978884#diff-eb12cee32bcf605b68363a07e95e0174R193)

API doco indicates that nil value should be valid, however I notice `oauth_test.go` passes `NoContext` value instead.

**Comment by adg** [comment]
Don't do that. `nil` contexts are wrong. At least use `context.TODO` or `oauth2.NoContext`.

**Comment by adg** [comment]
Opening to fix the docs

**Comment by adg** [comment]
https://go-review.googlesource.com/7615
