### ISSUE TITLE
Rename SetParam

### ISSUE THREAD

**Issue by rakyll** [golang/oauth2#108]
SetParam is vague to represent an AuthCodeOption maker. What about ExtraAuthCodeOption or NewAuthCodeOption?

cc/ @bradfitz

**Comment by bradfitz** [comment]
I like the "Set" part (it sets, as opposed to appends) and I like the "Param" part. It's a URL parameter. 

If you want to be more explicit, maybe "SetAuthURLParam"?

ExtraAuthCodeOption doesn't say that it sets (as opposed to appends) and doesn't say what sort of option it is. (i.e. we might add a header option in the future, but this is a URL option). I don't like "New" for the same reason. There might be other ways to make an AuthCodeOption if we've gone with the option parameter style already.

**Comment by rakyll** [comment]
SetAuthURLParam sounds like a good plan.

I used to be a bit close-minded about the AuthCodeOption -- may it really ever represent anything other than an URL parameter?

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/#/c/8491/.
