### ISSUE TITLE
PasswordCredentialsToken() sends client_id

### ISSUE THREAD

**Issue by vetinari** [golang/oauth2#110]
When retrieving a token with PasswordCredentialsToken() the [OpenAM](https://forgerock.org/openam/) OAuth2 Provider always fails, because an extra `client_id=somename` is sent with the request.
A diff like https://github.com/vetinari/oauth2/commit/2ddaf74e6a255aff61833524bc7ccf3b5191ada9 fixes the issue

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/#/c/8560/.

**Comment by vetinari** [comment]
Thanks, but that does not solve it completely, in that case c.ClientID is not empty / unset - it's used for BasicAuth at the provider...

**Comment by rakyll** [comment]
The password credentials flow requires its own TokenSource implementation. Otherwise, retrieveToken will end up being overly multi-purpose. I will take another look at this issue later.

**Comment by agtorre** [comment]
I'm currently doing a slight refactor of this (while trying to add client credentials grant). I'll add a TokenSource along the way.

**Comment by agtorre** [comment]
Actually pass on that, my pull request is focused on client credentials and it sounds like this will be looked at again later.

**Comment by mcqueenorama** [comment]
Anybody getting anywhere with this?

**Comment by drewwells** [comment]
This somewhat related to another issue. Access Token is sending client_id when authorization header is provided. The spec states that this is not required and some oauth2 servers will error if client_id is sent on authenticated requests: http://tools.ietf.org/html/rfc6749#section-4.1.3
