### ISSUE TITLE
Incorrect package name/url in app engine example google.golang.org/urlfetch

### ISSUE THREAD

**Issue by ianchildress** [golang/oauth2#116]
In the following example, google.golang.org/urlfetch should be google.golang.org/appengine/urlfetch

import (
    "golang.org/x/net/context"
    "golang.org/x/oauth2"
    "golang.org/x/oauth2/google"
    newappengine "google.golang.org/appengine"
    newurlftech "google.golang.org/urlfetch"

    "appengine"
)

func handler(w http.ResponseWriter, r *http.Request) {
    var c appengine.Context = appengine.NewContext(r)
    c.Infof("Logging a message with the old package")

    var ctx context.Context = newappengine.NewContext(r)
    client := &http.Client{
        Transport: &oauth2.Transport{
            Source: google.AppEngineTokenSource(ctx, "scope"),
            Base:   &newurlfetch.Transport{Context: ctx},
        },
    }
    client.Get("...")
}

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/#/c/9932/.
