### ISSUE TITLE
appengine import paths seems to be broken

### ISSUE THREAD

**Issue by robinwassen** [golang/oauth2#122]
When doing a clean `go get golang.org/x/oauth2` there are some issues with the import paths, see output below.

I have cleaned the pkg directory and deleted all dependencies to get a fresh version of all code.

**OS:** Mac OS X 10.10 64-bit
### Using go

```
robin@Robins-MacBook-Pro ~/dev/go/src/golang.org/x/oauth2 (master)$ go version
go version go1.4.2 darwin/amd64
robin@Robins-MacBook-Pro ~/dev/go/src/golang.org/x $ go get -u golang.org/x/oauth2
robin@Robins-MacBook-Pro ~/dev/go/src/golang.org/x $ cd oauth2/
robin@Robins-MacBook-Pro ~/dev/go/src/golang.org/x/oauth2 (master)$ go get -u ./...
robin@Robins-MacBook-Pro ~/dev/go/src/golang.org/x/oauth2 (master)$ go test ./...
# golang.org/x/oauth2/google
google/example_test.go:18:2: cannot find package "google.golang.org/appengine" in any of:
    /usr/local/go/src/google.golang.org/appengine (from $GOROOT)
    /Users/robin/dev/go/src/google.golang.org/appengine (from $GOPATH)
FAIL    golang.org/x/oauth2/google [setup failed]
ok      golang.org/x/oauth2 0.022s
ok      golang.org/x/oauth2/clientcredentials   0.014s
?       golang.org/x/oauth2/facebook    [no test files]
?       golang.org/x/oauth2/github  [no test files]
ok      golang.org/x/oauth2/internal    0.013s
?       golang.org/x/oauth2/jws [no test files]
ok      golang.org/x/oauth2/jwt 0.593s
?       golang.org/x/oauth2/linkedin    [no test files]
?       golang.org/x/oauth2/odnoklassniki   [no test files]
?       golang.org/x/oauth2/paypal  [no test files]
?       golang.org/x/oauth2/vk  [no test files]
```
### Using App Engine SDK

```
robin@Robins-MacBook-Pro ~/dev/go/src/golang.org/x/oauth2 (master)$ goapp version
go version go1.4.2 (appengine-1.9.20) darwin/amd64
robin@Robins-MacBook-Pro ~/dev/go/src/golang.org/x/oauth2 (master)$ goapp get ./...
client_appengine.go:16:2: cannot find package "google.golang.org/appengine/urlfetch" in any of:
    /Applications/go_appengine/goroot/src/google.golang.org/appengine/urlfetch (from $GOROOT)
    /Users/robin/dev/go/src/google.golang.org/appengine/urlfetch (from $GOPATH)
google/appengine_hook.go:9:8: cannot find package "google.golang.org/appengine" in any of:
    /Applications/go_appengine/goroot/src/google.golang.org/appengine (from $GOROOT)
    /Users/robin/dev/go/src/google.golang.org/appengine (from $GOPATH)
```

**Comment by adg** [comment]
I think you want `goapp get -u` in your latter case, because you may have an old version of the `google.golang.org/appengine` repo?

In the first case we should not make the tests depend on app engine.

**Comment by adg** [comment]
Fix: https://go-review.googlesource.com/10247

**Comment by adg** [comment]
Actually the above fix is wrong. You need to fetch test dependencies to run the tests. Try `go get -u -t` in the google directory.

**Comment by robinwassen** [comment]
@adg I tried `go get -u -t` and still have the same problem, also removed $GOPATH/pkg/ and most of $GOPATH/src/ without success.

**Comment by robinwassen** [comment]
@adg There still seems to be some issues with including the `oauth2` package in an app engine application though. Our automated builds which are checking out our application with dependencies fail to fetch all dependencies of `oauth2`.

**Steps I used to reproduce locally:**

Remove the directories `$GOPATH/pkg/`, `$GOPATH/code.google.com`, `$GOPATH/golang.org`, `$GOPATH/google.golang.org` and `$GOPATH/github.com/golang` to ensure no old versions exist.

Checkout our application which has a dependency on `"google.golang.org/cloud"` which in it's turn has a dependency on `oauth2`

Run `goapp get -t ./...` in the application directory.

**Result**

	robin@Robins-MacBook-Pro ~/dev/go/src/github.com/company/application (release)*$ goapp get -t ./...
	../../../golang.org/x/oauth2/google/appengine_hook.go:9:8: cannot find package "google.golang.org/appengine" in any of:
		/Applications/go_appengine/goroot/src/google.golang.org/appengine (from $GOROOT)
		/Users/robin/dev/go/src/google.golang.org/appengine (from $GOPATH)
	../../../golang.org/x/oauth2/client_appengine.go:16:2: cannot find package "google.golang.org/appengine/urlfetch" in any of:
		/Applications/go_appengine/goroot/src/google.golang.org/appengine/urlfetch (from $GOROOT)
		/Users/robin/dev/go/src/google.golang.org/appengine/urlfetch (from $GOPATH)

Will investigate further why this fails.

**Comment by robinwassen** [comment]
It works from clean slate if I start by explicitly fetch oauth2 before my other packages, so basically I run:
1. `goapp get -t golang.org/x/oauth2/...`
2. `goapp get -t ./...` (in the application directory)

Feels quite wrong to have to explicit get packages in the build script though.

**Comment by adg** [comment]
If you're going to run tests with dependencies, you need to fetch those
dependencies. I'm not sure what else we should suggest?
