### ISSUE TITLE
Unclear how to provide a custom http.Client

### ISSUE THREAD

**Issue by mmp** [golang/oauth2#123]
I may just be missing something, but it's unclear to me how to provide a custom http.RoundTripper to use with the *http.Client from the oauth2.Client method.

All that the documentation has to say is "The underlying HTTP transport will be obtained using the provided context", without any further information about what is being looked for in the values in the context.

If I dig through the oauth2 source code, I can find in internal/transport.go that I can only provide a custom http.Client (which would be fine), but doing so requires being able to make a variable of type internal.HTTPClient, which isn't exported.  So it doesn't seem possible for users of oauth2 to provide their own http.Client. Am I missing something?

**Comment by rakyll** [comment]
You need provide it through a value context.
```
ctx := context.WithValue(oauth2.NoContext, oauth2.HTTPClient, client)
```

**Comment by mmp** [comment]
...and now I see the HTTPClient variable (and its usage) documented at the very top of the godoc.  Thanks/sorry for the bother!
