### ISSUE TITLE
403 error while using Google JWT Service account for Analytics API

### ISSUE THREAD

**Issue by djinn** [golang/oauth2#125]
Hello,

I intended to recieve regular reports on page views and started building this dashboard. Sadly, I am facing problems. Request response looks like

```
{403 Forbidden 403 HTTP/1.1 1 1 map[X-Xss-Protection:[1; mode=block] Alternate-Protocol:[443:quic,p=1] Content-Type:[application/json; charset=UTF-8] Cache-Control:[private, max-age=0] Server:[GSE] Vary:[Origin X-Origin] X-Content-Type-Options:[nosniff] X-Frame-Options:[SAMEORIGIN] Www-Authenticate:[Bearer realm="https://accounts.google.com/", error=insufficient_scope, scope="https://www.googleapis.com/auth/analytics"] Date:[Fri, 05 Jun 2015 07:12:45 GMT] Expires:[Fri, 05 Jun 2015 07:12:45 GMT]] 0xc2081c6e20 -1 [chunked] false map[] 0xc208031ad0 0xc20829a080}
```

```golang 
package main

import (
        "fmt"
        "golang.org/x/oauth2"
        "golang.org/x/oauth2/google"
        //"golang.org/x/oauth2/jwt"
        "io/ioutil"
        "os"
)

func main() {
        // Your credentials should be obtained from the Google
        // Developer Console (https://console.developers.google.com).
        j, _ := os.Open("client_secret.json")
        e, _ := ioutil.ReadAll(j)
        conf, _ := google.JWTConfigFromJSON(e,
                "https://www.googleapis.com/auth/analytics.readonly",
                "https://www.googleapis.com/auth/analytics",
        )

        // Initiate an http.Client, the following GET request will be
        // authorized and authenticated on the behalf of user@example.com.
        tk := conf.TokenSource(oauth2.NoContext)
        client := conf.Client(oauth2.NoContext)
        fmt.Printf("%v  %v", client, tk)
        d, err := client.Get("https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3xxxxxxxx&start-date=30daysAgo&end-date=yesterday&metrics=ga%3Apageviews&dimensions=ga%3ApagePath%2Cga%3\
ApageTitle&sort=-ga%3Apageviews&filters=ga%3ApagePath%3D~%2Fp%2F")
        if err != nil {
                fmt.Printf("%v", err)
        }

        fmt.Printf("%v", d)

}
```
Do you think the problem is with the code or permissions in the google dev console?

**Comment by rakyll** [comment]
What's inside client_secret.json and why don't you handle errors?

**Comment by adg** [comment]
What kind of problems are you facing?

As @rakyll says, you need to check your errors otherwise you have no idea what's going on.

**Comment by pradpras** [comment]
Hi Experts,

I am facing a similar problem. Can you please help me
I have written a code to retrieve my google+ Domain user profile. 

1. I am using a google+ Domain Account with the domain name spaceandhow.com

2. I have provided all the privileges as listed in https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority

3. Both Google+ API and Google+ Domain Api are enabled on the account.

4. The json file used in the programme was downloaded from the service account during creation
as described in the aforementioned link

This is the function I have written.

    func (p *GoogleAUTH) sendGoogleAuthReq(){

        //os.Setenv("HTTP_PROXY", "http://proxyconf.glb.nsn-net.net/proxy.pac")
        fmt.Println("GoogleAUTH package: Enter sendGoogleAuthReq")


        data, err := ioutil.ReadFile("D:\\Cygwin\\home\\praprasa\\pragna2.json")
        if err != nil {
            fmt.Printf("ReadFile error: %s", err)
        }


        conf, err := google.JWTConfigFromJSON(data, "https://www.googleapis.com/auth/plus.me")
        if err != nil {
            fmt.Println("json error")

        }

        client := conf.Client(oauth2.NoContext)

        resp, err := client.Get("https://www.googleapis.com/plusDomains/v1/people/me")
        if err != nil {
            fmt.Printf("GoogleAUTH package: request execution failed: %s", err)
            return
        }
        defer resp.Body.Close()

        fmt.Println("GoogleAUTH package: response Status:", resp.Status)
        fmt.Println("GoogleAUTH package: response Headers:", resp.Header)

        body, err := ioutil.ReadAll(resp.Body)
        if err != nil {
            fmt.Printf("GoogleAUTH package: cannot fetch token: %v", err)
            return
        }

        fmt.Println("GoogleAUTH package: response Body:", string(body))

        fmt.Println("GoogleAUTH package: Exit sendGoogleAuthReq")   
    }


This is the error message i get

    GoogleAUTH package: response Status: 403 Forbidden
    GoogleAUTH package: response Headers: map[Vary:[Origin X-Origin] X-Frame-Options:[SAMEORIGIN] X-Xss-Protection:[1; mode=block] Cache-Control:[private, max-age=0] Server:[GSE] Date:[Sat, 29 Aug 2015 07:55:47 GMT] Content-Type:[application/json; charset=UTF-8] Expires:[Sat, 29 Aug 2015 07:55:47 GMT] X-Content-Type-Options:[nosniff] Alternate-Protocol:[443:quic,p=1] Alt-Svc:[quic=":443"; p="1"; ma=604800]]
    GoogleAUTH package: response Body: {
     "error": {
      "errors": [
       {
        "domain": "global",
        "reason": "forbidden",
        "message": "Forbidden"
       }
      ],
      "code": 403,
      "message": "Forbidden"
     }
    }


Thanks,
Pradyumna

**Comment by adg** [comment]
Try using the scope `"https://www.googleapis.com/auth/plus.login"` ?

**Comment by pradpras** [comment]
Hi Andrew,

Thanks you for your response.
I tried with both the scopes, individually and together.
 "https://www.googleapis.com/auth/plus.login" and "https://www.googleapis.com/auth/plus.me"

I get the same result

    GoogleAUTH package: response Status: 403 Forbidden
    GoogleAUTH package: response Headers: map[Date:[Thu, 10 Sep 2015 06:02:50 GMT] Expires:[Thu, 10 Sep 2015 06:02:50 GMT] X-Xss-Protection:[1; mode=block] Alternate-Protocol:[443:quic,p=1] Vary:[Origin X-Origin] X-Frame-Options:[SAMEORIGIN] Alt-Svc:[quic=":443"; p="1"; ma=604800] X-Content-Type-Options:[nosniff] Server:[GSE] Content-Type:[application/json; charset=UTF-8] Cache-Control:[private, max-age=0]]
    GoogleAUTH package: response Body: {
     "error": {
      "errors": [
       {
        "domain": "global",
        "reason": "forbidden",
        "message": "Forbidden"
       }
      ],
      "code": 403,
      "message": "Forbidden"
     }
    }

Thanks,
Pradyumna

**Comment by pradpras** [comment]
Hi Andrew,

Is there something else i can try out?

Thanks,
Pradyumna

**Comment by rakyll** [comment]
@pradpras, you can't use `plus.me` scope with a service account to resolve its owner user. The scope only allows you to retrieve who the me is if you have gone through the 3-legged OAuth 2.0 flow.  From the scopes page of the Domains API:

```
https://www.googleapis.com/auth/plus.me
Grants the app permission to use the special value me to represent
the authenticated user. Does not apply to apps that use domain-wide
delegation of authority.
```

https://developers.google.com/+/domains/authentication/scopes

**Comment by pradpras** [comment]
Hi @rakyll ,
I actually want to write an application that retrieves some service account specific data (just a string).
I realize that the 3 legged authentication needs user intervention ( to login to gmail).
I want to achieve this without user intervention.

I also read that it is possible to retrieve service account information using 2 legged authentication.

Using a normal service account, I am able to use the scopes "https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.login" and get "https://www.googleapis.com/plus/v1/people/me"

With this i get a successful response as below.

    GoogleAUTH package: response Status: 200 OK
    GoogleAUTH package: response Headers: map[Vary:[Origin X-Origin] X-Xss-Protection:[1; mode=block] Alternate-Protocol:[443:quic,p=1] Alt-Svc:[quic=":443"; p="1"; ma=604800] Date:[Tue, 15 Sep 2015 08:39:32 GMT] Cache-Control:[private, max-age=0, must-revalidate, no-transform] Content-Type:[application/json; charset=UTF-8] X-Content-Type-Options:[nosniff] X-Frame-Options:[SAMEORIGIN] Server:[GSE] Expires:[Tue, 15 Sep 2015 08:39:32 GMT] Etag:["gLJf7LwN3wOpLHXk4IeQ9ES9mEc/uQ0AhqWXsn6s5uGsJ3RVYt_c7mQ"] Content-Length:[462]]
    GoogleAUTH package: response Body: {
     "kind": "plus#person",
     "etag": "\"gLJf7LwN3wOpLHXk4IeQ9ES9mEc/uQ0AhqWXsn6s5uGsJ3RVYt_c7mQ\"",
     "objectType": "person",
     "id": "118383340478452440553",
     "displayName": "",
     "name": {
      "familyName": "",
      "givenName": ""
     },
     "image": {
      "url": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=50",
      "isDefault": true
     },
     "isPlusUser": false,
     "language": "en_US",
     "circledByCount": 0,
     "verified": false
    }

But if you notice, it has a bunch of default stuff that i cannot use for my purpose.
Would it be possible to save some data on this service profile and retrieve it with some API?

Please advise....

Thanks,
Pradyumna

**Comment by pradpras** [comment]
Just to add... I dont mind putting my string even in one of those fields   "familyName" or  "givenName" which are currently empty.
Can you suggest if there is a way to modify any of these values for the service profile?

Thanks,
Pradyumna

**Comment by rakyll** [comment]
Could you forward your questions to Google+ APIs team? I have limited knowledge about the API-specific functionality and limitations.
