### ISSUE TITLE
Provide ID token in TokenResponse

### ISSUE THREAD

**Issue by gguuss** [golang/oauth2#127]
Currently in order to get the OAuth 2.0 ID token, you must retrieve it by making a call to Extra, for example:

    tok.Extra("id_token").(string) 

Because this is a standard Token and is important for token verification, we should provide an accessor for the value to the oauth2 token object.

**Comment by gguuss** [comment]
I'll note, ID tokens are part of Open ID connect, which works on top of OAuth 2.0 - http://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken

**Comment by rakyll** [comment]
Closing for similar reasons why https://github.com/golang/oauth2/issues/128 is closed. Such utilities should live in an external package.
