### ISSUE TITLE
Provide token verification within oauth2 library

### ISSUE THREAD

**Issue by gguuss** [golang/oauth2#128]
Because ID token verification is an important step in AuthN systems that use OAuth2 / open ID connect, we should provide a convenience method that verifies tokens.  The following code does basic token verification:

    // decodeIdToken takes an ID Token and decodes it to fetch the Google+ ID within
    func decodeIdToken(idToken string) (gplusID string, err error) {                   
      fmt.Fprintf(os.Stderr, "dump: %s\n", idToken)                                    
      // An ID token is a cryptographically-signed JSON object encoded in base 64.  
      // Normally, it is critical that you validate an ID token before you use it,  
      // but since you are communicating directly with Google over an                  
      // intermediary-free HTTPS channel and using your Client Secret to               
      // authenticate yourself to Google, you can be confident that the token you   
      // receive really comes from Google and is valid. If your server passes the ID
      // token to other components of your app, it is extremely important that the  
      // other components validate the token before using it.                          
      var set ClaimSet                                                                 
      if idToken != "" {                                                               
        // Check that the padding is correct for a base64decode                        
        parts := strings.Split(idToken, ".")                                           
        if len(parts) < 2 {                                                            
          return "", fmt.Errorf("Malformed ID token")                                  
        }                                                                              
        // Decode the ID token                                                         
        b, err := base64Decode(parts[1])                                               
        if err != nil {                                                                
          return "", fmt.Errorf("Malformed ID token: %v", err)                         
        }                                                                              
        err = json.Unmarshal(b, &set)                                                  
        if err != nil {                                                                
          return "", fmt.Errorf("Malformed ID token: %v", err)                         
        }                                                                              
      }                                                                                
      return set.Sub, nil                                                              
    } 

Comprehensive information on ID tokens is available within the Open ID 1.0 spec - http://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken

**Comment by rakyll** [comment]
I can't see any mention of token IDs in the [OAuth 2.0 spec](https://tools.ietf.org/html/rfc6749). Is this a Google-specific feature just because Google had to deprecate OpenID?

If so, we should add the additional bits to the google package.

**Comment by gguuss** [comment]
It's actually relevant within the scope of [Open ID Connect](http://openid.net/specs/openid-connect-core-1_0.html), which is a common superset of OAuth 2.0 that includes claims about the user. [This blog post](https://www.tbray.org/ongoing/When/201x/2013/04/04/ID-Tokens) does a lot to affirm their utility.

**Comment by rakyll** [comment]
The verification utility function may fit in jws or jwt. It is tricky where it should live because the verification requires you to use your private key. We already have *Config types that require a private key and I am wondering if we can reuse any of the existing concepts.

cc/ @bradfitz for more feedback.

**Comment by themihai** [comment]
For what is worth I had the same issue and after several trials I ended-up with a dedicated openID package which imports both jose and oauth2. openID is built on top of oauth not the other way around and it has specific requirements/fields (i.e. standard claims) so it feels right to stay in a separate package.

**Comment by bradfitz** [comment]
Separate package sounds best to me.

**Comment by rakyll** [comment]
Separate package sounds good.

**Comment by adg** [comment]
+1

**Comment by adg** [comment]
I'm assuming @bradfitz and @rakyll mean a separate package outside the
oauth2 repo, that's why I closed the issue.

**Comment by rakyll** [comment]
I meant a package outside of the oauth2 repo. If anyone wants to contribute such a utility package elsewhere, I'd be happy to help and review it.

**Comment by ericchiang** [comment]
For anyone looking, we've implemented this feature over at https://github.com/coreos/go-oidc. Feedback welcome.
