### ISSUE TITLE
Work with Wunderlist

### ISSUE THREAD

**Issue by vlastv** [golang/oauth2#130]
API Wunderlist requires the transfer of the access token and cliend id.
The passkey must be passed not in the standard header.

Required headers:
```
X-Access-Token: OAUTH-TOKEN 
X-Client-ID: CLIENT-ID
```

How can I implement it using this library?

[Documentation](https://developer.wunderlist.com/documentation/concepts/authorization) for working with API

**Comment by rakyll** [comment]
We don't support API-specific support on the issue tracker, or support broken OAuth 2.0 implementations. If the package has a compliance problem with the OAuth 2.0 spec, please report the case.
