### ISSUE TITLE
MAC tokens not working

### ISSUE THREAD

**Issue by Kuzmin** [golang/oauth2#133]
Currently the Token.SetAuthHeader only adds the token type and access header to the Authorization header field. This does not work for MAC tokens, where the Authorization header needs to be calculated according to: http://tools.ietf.org/html/draft-ietf-oauth-v2-http-mac-01#section-3.1

Are pull requests for this welcome?

**Comment by adg** [comment]
That RFC is a draft. Did it ever get finalized?

**Comment by Kuzmin** [comment]
@adg: No, the only part of OAuth 2.0 that is finalized is Bearer tokens. However, this draft is already in use. For example, both Python's Requests library and Ruby's rack-oauth2 both implement this. It is also the draft referenced in the finalized RFC6749 "The OAuth 2.0 Authorization Framework". 

How do you view this, do you want to wait for the RFC to be finalized before adding MAC token support to the library? 

I think that adding support for the RFC in widespread use (in awaiting of the final version) would be a good thing that would let more users use this library for their authentication needs.

Thank you

(source reg. Ruby & Python: https://www.google.com/?gws_rd=ssl#q=%22tools.ietf.org%2Fhtml%2Fdraft-ietf-oauth-v2-http-mac-01%22+-site:ietf.org)

**Comment by adg** [comment]
(Sorry for the delayed reply.)

I'm not opposed to adding the feature, but how would the new one work? New
functions? New types? Please discuss the design here first.

**Comment by Kuzmin** [comment]
(Sorry from here too.)

Since you already provide the TokenType field, I think that the only change would be to add a field for the  `MacKey` and an optional field for the `MacAlgorithm` to the `Token` type. Then you would do a conditional check when setting auth headers, since that's really the only part of the code that changes.

I think it's reasonable to do it this way as long as it's clearly documented that the `Mac*` fields are only relevant for the Mac token. I feel like doing it with interfaces (which would be the next step the way I see it) would add a lot of additional overhead when the only thing that changes is the Auth header generation
