### ISSUE TITLE
Please add usage instructions for Application Default Credentials

### ISSUE THREAD

**Issue by vsubramani** [golang/oauth2#136]
adg@ had added support for the Application Default Credentials feature in this library. Please add usage instructions in the repro's readme file to help consumers. 

Here are some ruby and node example documentation for reference. 
https://github.com/google/google-auth-library-ruby
https://github.com/google/google-auth-library-nodejs

**Comment by bradfitz** [comment]
Fast forward almost 4 years and it looks like there are a number of examples at https://godoc.org/golang.org/x/oauth2/google 

So, closing this.
