### ISSUE TITLE
Jwt Access Credentials should cache JWTs

### ISSUE THREAD

**Issue by anthmgoogle** [golang/oauth2#140]
The JWT Access Credentials should temporarily cache JWTs. Suggested algorithm:
* Hash JWTs using Audience as key.
* Also store the timestamp of last use with each JWT.
* On access clear any JWT unused for more than 1 hour.

**Comment by adg** [comment]
Since a JWT Access Token can be computed on the fly with minimal cost, what's the point of caching them?

**Comment by anthmgoogle** [comment]
There are a pretty large payload in the request ~300 characters. We need to make sure HTTP 2.0 can avoid sending duplicates on repeated requests.

**Comment by adg** [comment]
I just updated the current implementation (
https://go-review.googlesource.com/10667) so that it'll re-use the same
token so long as it's valid (1 hour), and then issue a new one. (IOW, that
CL fixes this issue)
