### ISSUE TITLE
Golang program for retrieving google domain profile returns 403 forbidden

### ISSUE THREAD

**Issue by pradpras** [golang/oauth2#148]
Hi Experts,

I am facing a similar problem. Can you please help me
I have written a code to retrieve my google+ Domain user profile. 

1. I am using a google+ Domain Account with the domain name spaceandhow.com

2. I have provided all the privileges as listed in https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority

3. Both Google+ API and Google+ Domain Api are enabled on the account.

4. The json file used in the programme was downloaded from the service account during creation
as described in the aforementioned link

This is the function I have written.

    func (p *GoogleAUTH) sendGoogleAuthReq(){

        fmt.Println("GoogleAUTH package: Enter sendGoogleAuthReq")

        data, err := ioutil.ReadFile("D:\\Cygwin\\home\\praprasa\\pragna2.json")
        if err != nil {
            fmt.Printf("ReadFile error: %s", err)
        }

        conf, err := google.JWTConfigFromJSON(data, "https://www.googleapis.com/auth/plus.me")
        if err != nil {
            fmt.Println("json error")

        }

        client := conf.Client(oauth2.NoContext)

        resp, err := client.Get("https://www.googleapis.com/plusDomains/v1/people/me")
        if err != nil {
            fmt.Printf("GoogleAUTH package: request execution failed: %s", err)
            return
        }
        defer resp.Body.Close()

        fmt.Println("GoogleAUTH package: response Status:", resp.Status)
        fmt.Println("GoogleAUTH package: response Headers:", resp.Header)

        body, err := ioutil.ReadAll(resp.Body)
        if err != nil {
            fmt.Printf("GoogleAUTH package: cannot fetch token: %v", err)
            return
        }

        fmt.Println("GoogleAUTH package: response Body:", string(body))

        fmt.Println("GoogleAUTH package: Exit sendGoogleAuthReq")   
    }

This is the error message i get

    GoogleAUTH package: response Status: 403 Forbidden
    GoogleAUTH package: response Headers: map[Vary:[Origin X-Origin] X-Frame-Options:[SAMEORIGIN] X-Xss-Protection:[1; mode=block] Cache-Control:[private, max-age=0] Server:[GSE] Date:[Sat, 29 Aug 2015 07:55:47 GMT] Content-Type:[application/json; charset=UTF-8] Expires:[Sat, 29 Aug 2015 07:55:47 GMT] X-Content-Type-Options:[nosniff] Alternate-Protocol:[443:quic,p=1] Alt-Svc:[quic=":443"; p="1"; ma=604800]]
    GoogleAUTH package: response Body: {
     "error": {
      "errors": [
       {
        "domain": "global",
        "reason": "forbidden",
        "message": "Forbidden"
       }
      ],
      "code": 403,
      "message": "Forbidden"
     }
    }

Thanks,
Pradyumna

**Comment by rakyll** [comment]
If you ask Google APIs specific questions on the support mediums Google+ provides, you may get a faster response. This repo is the implementation of the OAuth 2.0 spec with helpers for Google's auth flows. None of us has expertise to answer API-specific questions.
