### ISSUE TITLE
proposal, google: Expose project ID

### ISSUE THREAD

**Issue by flowlo** [golang/oauth2#150]
As requested in the Go Contribution Guidelines I propose:

To expose the project ID of the current user by adding a function `Project() string` to `golang.org/x/oauth2/google.SdkConfig`.

This method would return a new unexposed property of `SDKConfig`, namely `projID string`, which is initialized by `NewSDKConfig(account string)`.

```go
// Project is the project configured for the current user. If no such
// project is set, it will be zero.
func (c *SDKConfig) Project() string {
	return c.projID
}
```

For the project ID to be read by `NewSDKConfig` it must be set in `~/config/gcloud/properties`:

````ini
[core]
account = foo@example.com
project = example
````

This is usually achieved by calling

````
$ gcloud config set --scope user project PROJECT
````

Considerations:
 1. `~/.config/gcloud/properties` is currently only read iff `account == ""` (`account` is an argument to `NewSDKConfig`). To retrieve the project ID, the file must be inspected. Trivially this would raise the constraint that `Project()` is only available iff `NewSDKConfig` was called with `account := ""`. Of course it would be possible to inspect `~/.config/gcloud/properties` even if `account == ""`
 2. If implemented like described, this will not catch project configuration on installation or workspace level.

I have [an implementation ready](https://github.com/golang/oauth2/compare/golang:master...flowlo:projid), but will wait for comments before submitting this for review.

**Comment by adg** [comment]
I don't outright object to this, but I have two concerns:

1. This would mean we now rely on the presence and stability of two files, instead of just one. I have been assured that `credentials` will stick around and stay the same, but I cant' say the same about the `properties` file. Maybe @broady knows, or knows who to ask?
2. What is the actual use case here? Why do you need to auto-detect the project ID?

**Comment by flowlo** [comment]
Regarding 2: For apps running on App Engine it is straightforward to retrieve the project identifier both locally with the development server and when deployed via [`appengine.AppID()`](https://godoc.org/google.golang.org/appengine#AppID). However, when developing for Compute Engine, retrieval of the project ID is (AFAIK) not possible, because [`cloud/metadata.ProjectID()`](https://godoc.org/google.golang.org/cloud/compute/metadata#ProjectID) needs to talk to the metadata server. The proposed addition would enable GCE targeted apps to find out their project ID in a development context.

**Comment by adg** [comment]
It seems to me the correct place for this is probably in the cloud/metadata
package, so that you can make the same API call to get the information
whether you're in dev or production. @okdave

**Comment by broady** [comment]
This is a tricky one.

I don't think the format of that config file is stable. Specifically, it's an implementation detail of the `gcloud` command.

We'd need to get a commitment from the gcloud SDK team about the format and location, etc, etc. before reading from it.

What are you actually using the project ID for? There may be better solutions to whatever you are trying to achieve :)

**Comment by flowlo** [comment]
@adg You are right, exposing this via `cloud/metadata` is the better place in terms of exposing it. I filed this here because `NewSDKConfig` felt like it would be the right way to read the `properties` file (there already is code that potentially looks at that file). And this is in `golang.org`, not `google.golang.org` so probably easier to get changes through (at least I think of it that way, might be completely wrong).

@broady It might sound silly but it's simple things like GCS bucket names that just happen to include the project ID. And I'd like to have a stable and generic way to get it, even when not running in the "real" GCE environment.

If you say this proposal does not have any prospects, that's fine.

**Comment by broady** [comment]
Let's get it in the right place. Something like this definitely belongs in `google.golang.org/cloud`. While you can't contribute directly there, someone at Google can. :+1: 

I've asked the Cloud SDK team internally if it's something we can safely depend on.

**Comment by flowlo** [comment]
OK, thanks! I'll be watching `google.golang.org/cloud/metadata` :P
