### ISSUE TITLE
Hard-coded expiry for JWT exceeds Salesforce limits

### ISSUE THREAD

**Issue by robnorman** [golang/oauth2#151]
The IETF draft states "Implementers MAY provide for some small leeway, usually no more than
a few minutes, to account for clock skew." https://tools.ietf.org/html/rfc7519#section-4.1.4

The current implementation of JWS/JWT in this package uses a fixed 1 hour expiry time for JWT tokens. That expiry can't be overridden as it relies on private struct properties. https://github.com/golang/oauth2/blob/master/jws/jws.go#L56

Some services do not accept such a long expiry time, e.g. Salesforce, which defaults to a 5 minute expiry. https://help.salesforce.com/HTViewHelpDoc?id=remoteaccess_oauth_jwt_flow.htm

We've already fixed this in a fork, but we're not willing to grant Gerrit access to our private repositories, and you don't accept GitHub PRs.

If you could allow this expiry to be overridden in the upstream code, e.g. as we've done in https://github.com/infinitytracking/oauth2/commit/0a40695d88f7286a87a832772d84937bdd5116ee that would be really helpful!

An alternative might be to reduce the hard-coded expiry to a few minutes, but that could introduce problems elsewhere.

**Comment by adg** [comment]
> We've already fixed this in a fork, but we're not willing to grant Gerrit access to our private repositories, and you don't accept GitHub PRs.

You don't need to grant Gerrit access to anything to send a change. You push your changes to the Go project's Gerrit server. Please send us a change :-)

**Comment by robnorman** [comment]
In the contrib guidelines it asks me to *"set up your account in Gerrit, visit go.googlesource.com and click on "Generate Password" in the page's top right menu bar"*
https://golang.org/doc/contribute.html#tmp_4

Following that link brings me to an auth request page where "\*.googlesource.com would like to: ... View and manage your Git repositories".

If there's a way around that I'd be happy to send a change.

**Comment by tomponline** [comment]
@adg yeah if we've missed something it would be great to know how to contribute without having to fully integrate with gerrit

**Comment by tomponline** [comment]
@adg @robnorman Is this what you mean? We can push directly to gerrit's server http://review.cyanogenmod.org/Documentation/user-upload.html using our google account as creds?

**Comment by adg** [comment]
On 11 September 2015 at 18:17, Rob Norman <notifications@github.com> wrote:

> Following that link brings me to an auth request page where "*.
> googlesource.com would like to: ... View and manage your Git
> repositories".
>
The Git repositories that message refers to are the ones hosted at
googlesource.com, ie the go repositories.

**Comment by robnorman** [comment]
Thanks @adg ...  kind of embarrassing I didn't check the URL when working with oauth2 :blush: 

Anyway, I've submitted a patch on Gerrit: https://go-review.googlesource.com/14681
