### ISSUE TITLE
Removing appenginevm build tag causes panics

### ISSUE THREAD

**Issue by derekperkins** [golang/oauth2#152]
Following up on the discussion here: https://github.com/golang/oauth2/commit/ad0128250e8fba646a92ca9129716e523d63ef9f

Removing the +appenginevm build tag causes a panic.
![image](https://cloud.githubusercontent.com/assets/3588778/9892651/1e97b0e2-5bce-11e5-87a1-d0ee08769139.png)

I don't understand the reasoning behind eliminating support. Maybe Managed VM users could also use the metadata server, but there doesn't seem to be any useful reason to eliminate the old support, especially in a type-unsafe way. It seems like people are supposed to be able to easily transition between classic App Engine and Managed VMs, and this commit eliminates that compatibility.

**Comment by derekperkins** [comment]
@broady @adg

**Comment by broady** [comment]
Can you tell me more about how/why you're using AppEngineTokenSource?

You might want to read the discussion on #142.

**Comment by derekperkins** [comment]
It's some older code from when we were using classic App Engine and has continued to work fine to create a client. It's not that I'm opposed to changing our code, it just seems like it will make the change from classic App Engine more difficult than necessary. If it's something you really want to stick with, please make it a compile error or at least not a panic.

```
GoogleClient := &http.Client{
	Transport: &oauth2.Transport{
		Source: google.AppEngineTokenSource(c,
			"https://www.googleapis.com/auth/bigquery",
			"https://www.googleapis.com/auth/devstorage.full_control",
			"https://www.googleapis.com/auth/cloud-platform",
		),
		Base: &urlfetch.Transport{
			Context: c.Context,
		},
	},
}
```

**Comment by broady** [comment]
What do you end up using that `http.Client` for?

Just trying to understand the use case. It must be something I didn't think of when I made the change.

**Comment by broady** [comment]
BTW, it's not possible to make this a compile-time error.

**Comment by derekperkins** [comment]
We use that for all of our BigQuery API interactions.

**Comment by broady** [comment]
@derekperkins  Please pull and try again.

**Comment by josephbergevin** [comment]
@broady that fixed it for us. Thanks.

**Comment by derekperkins** [comment]
Thanks a ton for the quick resolution @broady
