### ISSUE TITLE
Google and oauth2 issue

### ISSUE THREAD

**Issue by hariever** [golang/oauth2#153]
I've setup google oauth for my domain and it's working fine but a few things in my home page throwing 403. Upon checking via developer tools, the end points with /api throwing 403 but if I access them directly in the same browser it's showing the json content correctly. I feel like there is a double authentication required, not sure though. Can someone please shed some light on this. 

As per developer tools headers showing 403 error for /api urls , preview shows "sign in with google account screen"

**Comment by rakyll** [comment]
Could you please contact the Admin SDK support or their support channels? We don't have much expertise about specific Google APIs and our recommendations might be misleading.
