### ISSUE TITLE
Facebook long lived access token

### ISSUE THREAD

**Issue by alexdeefuse** [golang/oauth2#154]
Hi,

Is there a way I can use golang oauth2 to extend short lived facebook access tokens?
With the new version of Go 1.5 I cannot use the "internal" package.

What I used to do with the 1.4 version of go is:
```go
import (
      "golang.org/x/oauth2"
      "golang.org/x/oauth2/internal"
)

itk, err := internal.RetrieveToken(
        oauth2.NoContext,
        cfg.ClientID,
        cfg.ClientSecret,
        cfg.Endpoint.TokenURL,
        url.Values{
            "grant_type":        {"fb_exchange_token"},
            "fb_exchange_token": {tkn.AccessToken},
        },
    )
```

Is there a "supported" or "suggested" way to do this with Go 1.5 that doesn't allow the usage of the "internal" package?

Thanks,
Alex

**Comment by adg** [comment]
I suppose we could add support for this Facebook proprietary extension to the oauth2/facebook package. Got a link to the docs on `fb_exchange_token`? Or better yet, want to send [a change](https://golang.org/doc/contribute.html)?

**Comment by alexdeefuse** [comment]
Hi Andrew,

The docs can be found at:
https://developers.facebook.com/docs/facebook-login/access-tokens

You'll need to scroll all the way down to "Expiration and Extending Tokens".

I'm also keen to get involved into solving this. There are a few options that I see:

1. In the "facebook" package I see adding a "ExtendToken" function. The "facebook" package would import the "internal" package and use the "internal.RetrieveToken" function. (I must say I was surprised that I can use the "internal" package in sibling sub-packages. This never occured to me while reading https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit)

2. In the oauth2 package there is the "token.go" file where there is a unexported "retrieveToken" function. I cannot see a good reason why this would be unexported. I mean if this function would be exported then a lot of particular cases would have a simple solution and the library wouldn't have to deal with all these particularities.

What are your thoughts? I can see the appeal of the first method but please also consider case 2 explained above.

Best,
Alex

**Comment by adg** [comment]
I think `retrieveToken` on its own is a bit hard to decipher. Most users wouldn't know what to do with it, and having it around will just add to clutter in the package. I think we're better off just supporting the Facebook-specific functionality in the `oauth2/facebook` package.

As for option 1, what would the function signature of `ExtendToken` look like?

**Comment by alexdeefuse** [comment]
For the signature, I was thinking something like this:

```go
func ExtendToken(context.Context, *oauth2.Config, *oauth2.Token) (*oauth2.Token, error)
```

**Comment by adg** [comment]
It's not really obvious to me what it does or what it should do. What would the documentation say? (Sorry for the delayed response here.)

**Comment by rakyll** [comment]
How is extending token different from a token refresh?

**Comment by alexdeefuse** [comment]
@adg 

```go
// ExtendToken extends a short-lived access token (lifetime of about an hour or two) to a long-lived access token (lifetime of about 60 days) returning the latter on success.
func ExtendToken(context.Context, *oauth2.Config, *oauth2.Token) (*oauth2.Token, error) {
      // TODO: add content
}
```

**Comment by alexdeefuse** [comment]
@rakyll yes, they are. As I understand things from the facebook docs (excerpt and link posted below), the lifetime of the facebook token is directly linked to requests being made at regular time intervals so the token doesn't expire.

Facebook dev docs excerpt:

Native mobile apps using Facebook's SDKs will get long-lived access tokens, good for about 60 days. These tokens will be refreshed once per day when the person using your app makes a request to Facebook's servers. If no requests are made, the token will expire after about 60 days and the person will have to go through the login flow again to get a new token.

Access tokens on the web often have a lifetime of about two hours, but will automatically be refreshed when required. If you want to use access tokens for longer-lived web apps, especially server side, you need to generate a long-lived token. A long-lived token generally lasts about 60 days.

(taken from: https://developers.facebook.com/docs/facebook-login/access-tokens - "Expiration and Extending Tokens")

**Comment by rakyll** [comment]
Thanks for the reference. ExtendToken under oauth2/facebook sounds like a good option to me. Let's wait for @adg for consensus.

**Comment by adg** [comment]
Okay, this sounds good to me. Please go ahead and send a CL. Thanks.

**Comment by alexdeefuse** [comment]
I have a problem and would love to hear your thoughts about it. The problem is related to the oauth2.Token "raw" field. Because I'm writing my code in package "facebook" there is no way for me to populate this "raw" field (because Token belongs to package "oauth2").

Should I just ignore this raw field?

Here is what I have so far (including the commented out "raw" field):

```go
package facebook

import (
    "errors"
    "net/url"

    "golang.org/x/net/context"
    "golang.org/x/oauth2"
    "golang.org/x/oauth2/internal"
)

// ExtendToken extends a short-lived access token (lifetime of about an hour or two)
// to a long-lived access token (lifetime of about 60 days) returning the latter on success.
func ExtendToken(ctx context.Context, cfg *oauth2.Config, tkn *oauth2.Token) (*oauth2.Token, error) {
    if tkn.AccessToken == "" {
        return nil, errors.New("oauth2: short lived access token is not set")
    }   
    t, err := internal.RetrieveToken(
        ctx,
        cfg.ClientID,
        cfg.ClientSecret,
        cfg.Endpoint.TokenURL,
        url.Values{
            "grant_type":        {"fb_exchange_token"},
            "fb_exchange_token": {tkn.AccessToken},
        },
    )   
    if err != nil {
        return nil, err 
    }   
    return &oauth2.Token{
        AccessToken:  t.AccessToken,
        TokenType:    t.TokenType,
        RefreshToken: t.RefreshToken,
        Expiry:       t.Expiry,
        // raw:          t.Raw,
    }, nil 
}
```go

**Comment by rakyll** [comment]
Is Facebook returning other meta values as a part of the fb_exchance_token? It must be ok to ignore the raw if that's the case.

The raw field helps to read additional meta values returned as a part of the response, in addition to access token, token type, refresh token and expiry.

**Comment by alexdeefuse** [comment]
@rakyll all they return is below:

```go
map[expires:[5184000] access_token:[.........]]
```

Will try to send these changes now, fingers crossed.

**Comment by alexdeefuse** [comment]
Let me begin by saying sorry for wasting everyone's time.
I've done some more tests and it seems that the extend token call does absolutely nothing.
When the docs say "web login" they are referring to logins done using the javascript api they expose.
Found this out by implementing the login mechanisms both in javascript and go and then looking at the "expiration" fields.

Again, really sorry for wasting your time.

**Comment by tclass** [comment]
So I have to redirect the user every 1-2 hours or could I just do dummy requests to the Facebook API to hold the Access Token valid? How did you implement it @alexdeefuse (1-2 hours seems pretty short)

**Comment by alexdeefuse** [comment]
@tclass From what I understood from the FB docs and the tests I did, the expiration of a token is dictated by its type and the way you get that token. The 1-2 hours expiration period, I've been able to get an expiration of that length only by using JS to authenticate the user (so the auth process is started in the front-end using the JS lib FB exposes). If you use any backend method to auth the user, your expiration should be the longer one.

My comments above were relevant in the auth process being started on the front-end and then that token would have had to be passed to the "ExtendToken" method explained above.

If you're using using "oauth2" you should check the Token.Expiry to see how long the token will last. I'm sure that it will be 60 days but please check that.

Again, this is what I found out and I did write code to obtain a FB access token with both js and go.

Hope it helps.

**Comment by lukashes** [comment]
Its useful feature to retrive long-live token.

**Comment by rakyll** [comment]
@alexdeefuse, according to the docs explained at https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension, a typical use case for extending a token could be doing the consent-requesting login on the frontend and extending the token (with the use of the short-lived token) on the server. `ExtendToken` could still be a useful functionality for this use case.

**Comment by alexdeefuse** [comment]
@rakyll Indeed, as I mentioned in one of my previous comments, the "ExtendToken" would be a method that could be used with the JS library FB exposes. I will send a pull request ASAP to cover this case.

**Comment by narqo** [comment]
It's been two years since the original issue was described, but at least current version of Facebooks's API docs has a topic about obtaining long-lived access tokens on the server-side. See "Generating Long-Lived Tokens from Server-Side Long-Lived Tokens" https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension#long-via-code

@rakyll @adg do you still think oauth2/facebook is the right place to add some helpers for long-lived tokens retrieving? I have to implement this very custom refreshment process for facebook's tokens in our internal project, and I'd be happy to do some contribution to oauth2 package.
