### ISSUE TITLE
TLS Certificate problems with Github OAuth2

### ISSUE THREAD

**Issue by andrewwatson** [golang/oauth2#157]
I'm trying to build/deploy a simple web app on GAE that uses GitHub OAuth2 as a login system but when my app reaches out to fetch the token I get an SSL error:

2015/11/02 03:55:34 CRITICAL: oauthConf.Exchange() failed with 'Post https://github.com/login/oauth/access_token: API error 6 (urlfetch: SSL_CERTIFICATE_ERROR): [Errno 1] _ssl.c:503: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed'

The GitHub cert seems fine, it's using a SHA2 hash but my browser has no issues with it.  I'm wondering if it's a Go 1.4 issue since GAE is still on 1.4.  Has anyone had any experience getting this to work?

**Comment by tylerd-porch** [comment]
You may need to add a custom http client with certificates included in its Pool. I'm not sure if GAE provides the appropriate certs. 

Example: https://github.com/kelseyhightower/contributors
Or my own: https://github.com/tydavis/curlgo

**Comment by broady** [comment]
I think this is something to do with the root CA.

@andrewwatson, I know we talked about this already, but are you still seeing this?

**Comment by jlubawy** [comment]
I believe this is an issue with the Go App Engine SDK using an invalid/outdated certificate chain.

See if my solution here helps: https://code.google.com/p/googleappengine/issues/detail?id=12588

**Comment by rakyll** [comment]
I am going to close this issue, I think it should be reported/tracked at the App Engine issue tracker. https://code.google.com/p/googleappengine/issues/list

Please let us know if there is anything to be fixed on our side.
