### ISSUE TITLE
Please add Salesforce to brokenAuthHeaderProviders

### ISSUE THREAD

**Issue by ohler** [golang/oauth2#163]
Pull request #135 did this but was reverted: https://github.com/golang/oauth2/pull/135/files

The prefixes could probably be as specific as
`"https://login.salesforce.com/services/oauth2/"` and
`"https://test.salesforce.com/services/oauth2/"`, according to [their documentation](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_oauth_endpoints.htm).  I've tested `login.` but not `test.`.

**Comment by adg** [comment]
I sent this change:

https://go-review.googlesource.com/16856
