### ISSUE TITLE
Post : unsupported protocol scheme ""

### ISSUE THREAD

**Issue by ssenthil416** [golang/oauth2#167]
Below go lang code gives these error "Post : unsupported protocol scheme ""

How to resolve this error or what mistake is done

package main
import (
       "fmt"
       "golang.org/x/oauth2"
)
func main() {
    conf := &oauth2.Config{}
    tok, err := conf.PasswordCredentialsToken(oauth2.NoContext,"test","test1")
    if err != nil {
       fmt.Println("err is", err)
    }
    fmt.Println("token is ", tok)
}

**Comment by rakyll** [comment]
Zero configs are not valid. We should probably return a better error message here.

``` go
	conf := &oauth2.Config{
		Scopes:       []string{"SCOPE1", "SCOPE2"},
		Endpoint: oauth2.Endpoint{
			AuthURL:  "https://provider.com/o/oauth2/auth",
			TokenURL: "https://provider.com/o/oauth2/token",
		},
	}
```

**Comment by ssenthil416** [comment]
I tried with above config, but still got error like 
err is Post https://provider.com/o/oauth2/token: tls: oversized record received with length 20291
token is  <nil>

**Comment by rakyll** [comment]
`https://provider.com/o/oauth2/token` is not a real authorization token endpoint. Please replace it with the actual authorization and token endpoints of your OAuth 2 provider.
