### ISSUE TITLE
Converting internal.Token to oauth2.Token

### ISSUE THREAD

**Issue by jpmonette** [golang/oauth2#168]
I'm trying to convert `internal.Token` to `oauth2.Token` when using a broken auth (Salesforce), but my code doesn't seem to work right.

```go
tok, err := internal.RetrieveToken(oauth2.NoContext, conf.ClientID, conf.ClientSecret, conf.Endpoint.TokenURL, nil)
tok2 := oauth2.Token(*tok)
client := conf.Client(oauth2.NoContext, &tok2)
```

Error:

```
# command-line-arguments
./main.go:33: cannot convert *tok (type internal.Token) to type oauth2.Token
```

Any clue what I could do to make this work?

Thanks

**Comment by rakyll** [comment]
You are not supposed to import the internal package. Go 1.5+ doesn't even allow you to import import packages. Why do you import the internal package? `internal.RetrieveToken` is an internal implementation detail you should never care about.
