### ISSUE TITLE
CodePlex requires state parameter for token exchange

### ISSUE THREAD

**Issue by purpleKarrot** [golang/oauth2#169]
According to the documentation (https://www.codeplex.com/site/developers/api/authentication), the same `state` parameter used for authorize is also required to exchange a token.

Is this another spec violation?

**Comment by rakyll** [comment]
`state` is recommended but not enforced by the spec in authorization requests (see https://tools.ietf.org/html/rfc6749#section-4.1.1). The client should allow passing a state parameter though.

We need to break the current APIs in order to properly implement the spec.

/cc @adg

**Comment by adg** [comment]
The `oauth2.Config.AuthCodeURL` method already takes a `state` argument, so we already implement the spec for Authorization Requests (4.4.1).

The CodePlex docs say that a 'state' parameter is required for Access Token requests (which I believe is what @purpleKarrot is pointing to). This is not what the oauth2 spec says (see [4.4.3 - Access Token Request](https://tools.ietf.org/html/rfc6749#section-4.1.3)). I think CodePlex is wrong.

**Comment by rakyll** [comment]
Sorry for the noise. The state parameter provide protection from CSRF attacks. In the scope of authorization requests, it is not needed.
