### ISSUE TITLE
Where is twitter oauth support?

### ISSUE THREAD

**Issue by netroby** [golang/oauth2#175]
Where is twitter oauth support?

**Comment by netroby** [comment]
https://dev.twitter.com/web/sign-in/implementing
the oauth login dev guide

**Comment by adg** [comment]
Out of the scope of this package.

**Comment by goenning** [comment]
Hey @adg, can we have a bit more information on why it is out of scope? It is something that Twitter does not support? I couldn't find anything on this regard. Thanks!

**Comment by rakyll** [comment]
Twitter provides an endpoint for Client Credentials OAuth 2.0 flow, https://dev.twitter.com/oauth/application-only, which is supported by this library. Twitter's OAuth1 service is not supported given this library is an implementation of the OAuth 2.0 spec.
