### ISSUE TITLE
Internal package imports brakes builds for go 1.6 when vendored

### ISSUE THREAD

**Issue by jimenez** [golang/oauth2#178]
When building with go 1.6 or 1.5 with experimental vendoring enabled, I have the following error:

```sh
$ go build
package XXXX
    imports golang.org/x/oauth2
    imports golang.org/x/oauth2/internal: use of internal package not allowed
```

How to reproduce: 
`go build` the following code and make sure it builds:

```go
package main

import (
	"fmt"

	"golang.org/x/oauth2"
)

func main() {
	fmt.Println(oauth2.AccessTypeOnline)
}
```

then  `godep save` with go 1.6 or go 1.5 + `export GO15VENDOREXPERIMENT=1`, it will create the Godeps and vendor folders. 
Then try to build again with `go build` (is going to use the files in vendor this time) and fail because of the use of the internal package.

**Comment by adg** [comment]
Can you please provide more information? Perhaps the output of `find . -type d` from the parent of the `vendor` directory?

**Comment by jimenez** [comment]
Hi @adg, 

Here's the result `find . -type d` from the parent of the `vendor` directory of the example I describe above:

```sh
.
./vendor
./vendor/golang.org
./vendor/golang.org/x
./vendor/golang.org/x/oauth2
./Godeps
```

And here is a simple `find .` for the whole view:
```sh
.
./main.go
./vendor
./vendor/golang.org
./vendor/golang.org/x
./vendor/golang.org/x/oauth2
./vendor/golang.org/x/oauth2/CONTRIBUTING.md
./vendor/golang.org/x/oauth2/.travis.yml
./vendor/golang.org/x/oauth2/AUTHORS
./vendor/golang.org/x/oauth2/client_appengine.go
./vendor/golang.org/x/oauth2/LICENSE
./vendor/golang.org/x/oauth2/README.md
./vendor/golang.org/x/oauth2/token.go
./vendor/golang.org/x/oauth2/CONTRIBUTORS
./vendor/golang.org/x/oauth2/transport.go
./vendor/golang.org/x/oauth2/oauth2.go
./Godeps
./Godeps/Readme
./Godeps/Godeps.json
```

**Comment by jimenez** [comment]
@adg thanks, 
`godep save ./...` solves my problem.

**Comment by mh-cbon** [comment]
Hi @adg 

I would like to re open this bug.

I m facing the problem.


```sh
$ find . -type d
...
./vendor/github.com/golang
./vendor/github.com/golang/oauth2
./vendor/github.com/golang/oauth2/linkedin
./vendor/github.com/golang/oauth2/internal
./vendor/github.com/golang/oauth2/microsoft
./vendor/github.com/golang/oauth2/bitbucket
./vendor/github.com/golang/oauth2/slack
./vendor/github.com/golang/oauth2/fitbit
./vendor/github.com/golang/oauth2/vk
./vendor/github.com/golang/oauth2/github
./vendor/github.com/golang/oauth2/paypal
...

$ go run main.go list-auth ..
package main
	imports github.com/golang/oauth2
	imports golang.org/x/oauth2/internal: use of internal package not allowed

$ cat main.go
package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"syscall"

	"github.com/google/go-github/github"
	"github.com/mh-cbon/gh-api-cli/GenVersionFile"
	"github.com/mh-cbon/gh-api-cli/gh"
	"github.com/mh-cbon/gh-api-cli/local"
	"github.com/urfave/cli"
	"golang.org/x/crypto/ssh/terminal"
	"github.com/golang/oauth2"
	"github.com/mattn/go-zglob"
)
...
```

I m unsure why go works like [this](https://github.com/golang/go/blob/0deb49f9c09d15bf0e4c5ec843bd374f9a377e97/src/cmd/go/pkg.go#L511)

Is it possible to implement a simple work around ?

thanks!

**Comment by adg** [comment]
@mh-cbon you're importing the package as `github.com/golang/oauth2` when its canonical import path is `golang.org/x/oauth`. Rename the directory hierarchy and your imports and it should work fine.

**Comment by mh-cbon** [comment]
worked for me, 

really just
```
  // "github.com/golang/oauth2"
  "golang.org/x/oauth2"
```

thanks, sorry for that!

**Comment by renannprado** [comment]
I'm importing `golang.org/x/oauth2` and still get the same issue.
Should I vendor `github.com/golang/oauth2` instead?

**Comment by llitfkitfk** [comment]
need `rm -rf vendor/` then `godep save ./...`

**Comment by BaSO4** [comment]
please try govendor add +outside
