### ISSUE TITLE
Set User-Agent?

### ISSUE THREAD

**Issue by alltom** [golang/oauth2#179]
I'm using the reddit API, which frequently returns HTTP 429 unless you set a custom User-Agent header. Is there a hook for setting that header?

**Comment by rakyll** [comment]
You can set a base custom RoundTripper on https://godoc.org/golang.org/x/oauth2#Transport. The custom RoundTripper could modify each request object to set a user-agent.

Leaving a very rough pseudo code like example below.
```
type uaSetterTransport struct{}

func (t *uaSetterTransport) RoundTrip(req *http.Request) (*http.Response, error) {
    // modify req here
}

tr := oauth2.Transport{
     TokenSource: conf.TokenSource(oauth2.NoContext, tok)
     Base: &uaSetterTransport{}
}

c := &http.Client{Transport: tr}
```

**Comment by rmichela** [comment]
@rakyll Can you be more explicit with your pseudocode? I'm not able to piece enough together to understand what you mean. Am I supposed to setup a context for calling Exchange()? If so, what am I supposed to put in it? 

How do I associate a Transport with the call to Exchange()?

**Comment by rakyll** [comment]
@rmichela,

You can exchange with a custom HTTP client:

```
var c *http.Client //...
var config *oauth2.Config // ...

ctx = context.WithValue(ctx, oauth2. HTTPClient, c)
config.Exchange(ctx, code)
```

**Comment by rmichela** [comment]
Thanks,
Here's what I've done. It seems to work. https://github.com/rmichela/go-reddit/blob/bd882abbb7496c54dbde66d92c35ad95d4db1211/authenticator.go#L117
