### ISSUE TITLE
ConfigFromJSON cred struct outdated?

### ISSUE THREAD

**Issue by shyamsalimkumar** [golang/oauth2#185]
> What version of Go are you using (go version)?
> What operating system and processor architecture are you using?

```bash
$ go version
go version go1.5.1 linux/amd64
```

> What did you do?

Copy pasted the [example code](https://developers.google.com/sheets/quickstart/go#step_3_set_up_the_sample) and ran it.

> What did you expect to see?

Data from the spreadsheet that the code is supposed to try to read.

> What did you see instead?

```bash
$ go run main.go 

2016/05/25 13:16:42 Unable to parse client secret file to config: oauth2/google: no credentials found
exit status 1
```

I noticed that the client secret file downloaded from the Google App console doesn't correspond to [this structure](https://github.com/golang/oauth2/blob/master/google/google.go#L45-54) instead it looks more like 

```json
{
  "type": "",
  "project_id": "",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "",
  "token_uri": "",
  "auth_provider_x509_cert_url": "",
  "client_x509_cert_url": ""
}
```
Above is the structure of the JSON file I got when I selected that this would be running using a cron/daemon.

**Comment by adg** [comment]
@okdave is it likely that the cloud console has changed its export format? 😢

**Comment by okdave** [comment]
That seems like it would be a big breaking change. I'll have to look.

**Comment by rakyll** [comment]
@shyamsalimkumar, what's your client_secret.json is like and where did you download it from? Could you share us the JSON layout (not the credentials themselves) from that file?

**Comment by shyamsalimkumar** [comment]
@rakyll I'd inserted the structure in the first message

> I noticed that the client secret file downloaded from the Google App console doesn't correspond to this structure instead it looks more like
> 
> {
>   "type": "",
>   "project_id": "",
>   "private_key_id": "",
>   "private_key": "",
>   "client_email": "",
>   "client_id": "",
>   "auth_uri": "",
>   "token_uri": "",
>   "auth_provider_x509_cert_url": "",
>   "client_x509_cert_url": ""
> }
> 
> Above is the structure of the JSON file I got when I selected that this would be running using a cron/daemon.

I'm not sure if the client_secret.json strucutre is still the same (if I were to take a new client_secret.json) as its been a while.

**Comment by rakyll** [comment]
The schema is unchanged and the Google secret keys are working for me. Can you make sure that the key you are passing to JWTConfigFromJSON is correct?

**Comment by shyamsalimkumar** [comment]
Weird... Got a different structure from before and it worked. :smile: 
The current `client_secret.json` structure is as follows.
```json
{
  "installed": {
    "client_id": "",
    "project_id": "",
    "auth_uri": "",
    "token_uri": "",
    "auth_provider_x509_cert_url": "",
    "client_secret": "",
    "redirect_uris": []
  }
}
```

**Comment by zkynet** [comment]
I can confirm that when you first create your credentials you get this format:

{
"type": "",
"project_id": "",
"private_key_id": "",
"private_key": "",
"client_email": "",
"client_id": "",
"auth_uri": "",
"token_uri": "",
"auth_provider_x509_cert_url": "",
"client_x509_cert_url": ""
}

Once you download it again from the UI you get this format:

{
  "installed": {
    "client_id": "",
    "project_id": "",
    "auth_uri": "",
    "token_uri": "",
    "auth_provider_x509_cert_url": "",
    "client_secret": "",
    "redirect_uris": []
  }
}

As of today this is still broken.

**Comment by juliardi** [comment]
How do you generate the second format? I've tried to generate it several times, but always got the first format

**Comment by zkynet** [comment]
First you have to go into the edit screen for your credentials then you have to press "download json". 

This download json option seems to only be valid from within the edit view of each credential.

**Comment by juliardi** [comment]
@zkynet I don't find any "download json" text/button in my credentials edit screen, are there maybe something I miss? 
Here is how I generate the JSON config : 
1. Open Credentials page
2. Click "Create credentials" button, and select "Service account key" in the dropdown
3. Select my service account and key type as "JSON"
The generated JSON file is in the first format you mentioned.

**Comment by zkynet** [comment]
Try selecting the "OAuth Client ID" type of credentials. That's the one that will give you the download option with the new format

**Comment by juliardi** [comment]
@zkynet thank you, it's working. I got the second JSON format by selecting the "OAuth Client ID"

**Comment by zkynet** [comment]
Glad I could help !

**Comment by temamagic** [comment]
The same issue through the years...
