### ISSUE TITLE
scope is sent on access_token exchange

### ISSUE THREAD

**Issue by drewwells** [golang/oauth2#188]
Scope is not listed as a parameter for the access_token exchange in the spec. http://tools.ietf.org/html/rfc6749#section-4.1.3 So this can cause issues if the oauth server verifies each parameter is valid.

**Comment by plalloni** [comment]
This is fixed in #146 and submitted for review at https://go-review.googlesource.com/#/c/23790/.

**Comment by rakyll** [comment]
I am in favor of merging https://go-review.googlesource.com/#/c/23790/ if we can find an opportunity to verify it for the existing providers.
