### ISSUE TITLE
jws: base64Encode / base64Decode: Why not just use base64.RawURLEncoding?

### ISSUE THREAD

**Issue by ramoas** [golang/oauth2#190]
Is there a good reason why jws.base64Encode and jws.base64Decode are not just using base64.RawURLEncoding?

It seems like jws.base64encode should just call base64.RawURLEncoding.EncodeToString(b) (no TrimRight needed):
https://github.com/golang/oauth2/blob/master/jws/jws.go#L178-L180

Similarly, it seems like jws.base64decode should just call base64.RawURLEncoding.DecodeString(s) (no switch needed):
https://github.com/golang/oauth2/blob/master/jws/jws.go#L183-L194

Am I missing something obvious?  Did the jws package pre-date the introduction of base64.RawURLEncoding?

**Comment by okdave** [comment]
At the time this library was written we needed to support Go 1.4. We now only support 1.5+ (and these Raw versions were [introduced in 1.5](https://golang.org/doc/go1.5#minor_library_changes)), so we can make this simplification. Thanks for pointing it out.

**Comment by ramoas** [comment]
@okdave I only started using GO after 1.5 :)  Thanks for implementing the cleanup.
