### ISSUE TITLE
Dependencies are not properly installed when using App Engine SDK

### ISSUE THREAD

**Issue by robinwassen** [golang/oauth2#194]
**Steps to reproduce:**
- Install the latest App Engine SDK 1.9.40 
- Setup the $GOROOT and $GOPATH
- Run `goapp get golang.org/x/oauth2`

**Expected results:** The oauth2 pkg and dependencies should install

**Actual results:** The oauth2 dependency "google.golang.org/appengine/urlfetch" fails to be installed.

**Manual work around:** Run `goapp get --tags appengine golang.org/x/oauth2`

I tried to find a clean proper fix for this, but when I looked into this it seems like it can be related to goapp get not setting the proper tags rather than problems in this package. Just dropping this issue here for if someone else runs into this issue.

**Comment by rakyll** [comment]
Is this still an issue or closed because you were able to find a solution?
