### ISSUE TITLE
Add Accept: header when constructing http.Request

### ISSUE THREAD

**Issue by asergeyev** [golang/oauth2#200]
It looks like there are APIs authors who historically worked with XML/JSON apis and written their OAUTH endpoints in similar manner.  I don't think I should be calling out names here...

While it's not required by RFC, the "Accept: application/json" header would be nice addition to all token requests (I also wonder if http client just by default should send Accept: */* but it's probably separate and bigger discussion)

**Comment by rakyll** [comment]
You can construct your own oauth2.Transport and use a base RoundTripper that modifies the request instance. I'd be glad to share a snippet if you need one.

**Comment by asergeyev** [comment]
Thanks. I'll manage.

**Comment by stiangrindvoll** [comment]
Hi @rakyll, i would actually like to see an example of this!
I tried adding similar header for client credentials flow, but find my requests flying wild in endless loop.

**Comment by rakyll** [comment]
This is working for the 3-legged, and should work for the client credentials flow. Please open an issue if anything unexpected is happening.

```
package main

import (
	"context"
	"log"
	"net/http"

	"golang.org/x/oauth2"
)

type transport struct{}

func (t *transport) RoundTrip(req *http.Request) (*http.Response, error) {
	// Modify the request here.
	return http.DefaultTransport.RoundTrip(req)
}

func main() {
	hc := http.Client{Transport: &transport{}}
	ctx := context.WithValue(context.Background(), oauth2.HTTPClient, hc)

	conf := &oauth2.Config{
		ClientID:     "YOUR_CLIENT_ID",
		ClientSecret: "YOUR_CLIENT_SECRET",
		Scopes:       []string{"SCOPE1", "SCOPE2"},
		Endpoint: oauth2.Endpoint{
			AuthURL:  "https://provider.com/o/oauth2/auth",
			TokenURL: "https://provider.com/o/oauth2/token",
		},
	}

	tok, err := conf.Exchange(ctx, "foo")
	if err != nil {
		log.Fatal(err)
	}

}
```

**Comment by stiangrindvoll** [comment]
Thank you @rakyll, this lead me in the right direction.
Your example should however pass the "hc" as a reference, as seen with how ContextClient handles the context value for HTTPClient.

e.g.
`
hc := &http.Client{Transport: &transport{}}
`

```
internal/transport.go:35
func ContextClient(ctx context.Context) (*http.Client, error) {
	if ctx != nil {
		if hc, ok := ctx.Value(HTTPClient).(*http.Client); ok {
			return hc, nil
		}
	}
```

**Comment by rakyll** [comment]
You are right, you are supposed to pass the pointer. I am going to add this as an example to the package, so we can have a defacto tested example.
