### ISSUE TITLE
go get not working

### ISSUE THREAD

**Issue by pjebs** [golang/oauth2#201]
```
iMac:~ PJEBS$ go get -u golang.org/x/oauth2
# cd /Developer/Projects/GOPATH/src/golang.org/x/oauth2; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package golang.org/x/oauth2: exit status 1
```

**Comment by yanpozka** [comment]
Your output looks weird, first you're doing a go get and then you're a super user (# cd ...), also those errors are git output, no from **go get**

Try to do a ```go get -v -u golang.org/x/oauth2``` and you'll see how it download all the dependencies. At least it's working for me.

**Comment by pjebs** [comment]
Can you try deleting out the package from GOPATH and then go getting it again and see if it works?
It simply does not work for me. It spits out those git messages. EVERY OTHER PACKAGE I GO GET WORKS! lol

**Comment by xoraes** [comment]
+1

**Comment by rakyll** [comment]
Delete the package from GOPATH and go get it again. Your package is modified and git is refusing to pull from upstream.

**Comment by dhavlev** [comment]
Specifically delete the src/golang.org folder

**Comment by clock21am** [comment]
didn't work for me that way I can say

**Comment by clock21am** [comment]
I had to delete the entire src folder in order to get it to work still searching for the reason let me know if anyone of you has it

**Comment by shankernaik** [comment]
@rakyll Worked for me. Thanks! :)

**Comment by cr0w-C** [comment]
@rakyll that was very helpful worked for me

**Comment by Asadbe** [comment]
it`s worked thanks
