### ISSUE TITLE
Google hosted domain login

### ISSUE THREAD

**Issue by ericuldall** [golang/oauth2#204]
Does this library have support for the Google login hd param? I don't see it documented and can't find it anywhere in the code.

https://developers.google.com/identity/protocols/OpenIDConnect#hd-param

**Comment by rakyll** [comment]
This package is an implementation of https://tools.ietf.org/html/rfc6749, hd is not specified by the OAuth 2.0 spec.

**Comment by ericuldall** [comment]
Am I able to add extra parameters to the AuthCodeURL ? I'm trying SetAuthURLParam and it doesn't seem to exist.

**Comment by ericuldall** [comment]
Ah. Looks like it's oauth2.SetParam in the version I'm using. TY.
