### ISSUE TITLE
clientcredentials: audience parameter not supported

### ISSUE THREAD

**Issue by neelance** [golang/oauth2#216]
I would like to use the `clientcredentials` package for https://auth0.com/docs/api-auth/config/asking-for-access-tokens. Unfortunately that endpoint requires an `audience` parameter which is currently not supported.

I had a PR prepared at #215 because I didn't realize that this repo also follows the process via Gerrit. I respect that process for the main Go repo, but please understand that I don't want to go through that setup hassle for a 7 line change on a project with just 271 commits. It would be really helpful if someone could shepherd the change into master.

**Comment by shurcooL** [comment]
> It would be really helpful if someone could shepherd the change into master.

I tried, but I don't think I can do it while preserving you as author of commit.

```
$ git codereview mail
remote: Processing changes: refs: 1, done    
remote: 
remote: ERROR:  In commit 471d707c62628fdbc68e41552bd64395dc8ed81e
remote: ERROR:  author email address richard-musiol@...
remote: ERROR:  does not match your user account.
remote: ERROR:
remote: ERROR:  The following addresses are currently registered:
remote: ERROR:    shurcool@...
remote: ERROR:
remote: ERROR:  To register an email address, please visit:
remote: ERROR:  https://go-review.googlesource.com/#/settings/contact
remote: 
remote: 
To https://go.googlesource.com/oauth2
 ! [remote rejected] HEAD -> refs/for/master (invalid author)
error: failed to push some refs to 'https://go.googlesource.com/oauth2'
(running: git push -q origin HEAD:refs/for/master)
git-codereview: exit status 1
```

In any case, it'd be better if you made the CL, in case there's feedback, you could address review comments directly.

**Comment by rakyll** [comment]
For CLA-related reasons, the original author is expected to open the CL themselves.

**Comment by rakyll** [comment]
Re: audience

Audience is not a part of the OAuth 2.0 spec, we shouldn't add it as a field to the Config types. Though, we might think about giving users APIs so that they can modify the token URLs. Adding arbitrary query parameters to token URLs have been asked earlier.

**Comment by neelance** [comment]
I just realized that I'll have to set up Gerrit again for a change that I want to get into the main Go repo soon. I'm already a contributor to the Go project so the CLA is already covered.

@rakyll Do we want to add those arbitrary query parameters at the `clientcredentials` level or some more generic one?

**Comment by neelance** [comment]
New CL here: https://go-review.googlesource.com/#/c/36880/

**Comment by rakyll** [comment]
I was wondering if we can add something to oauth2.Endpoint like

```
func (e *Endpoint) SetTokenURLParam(..) ...
```

**Comment by rakyll** [comment]
Out of curiosity, is it possible to set a TokenURL with an `audience` query parameter?

**Comment by neelance** [comment]
Good idea, but unfortunately it doesn't work. I just tested it with the Auth0 endpoint and it seems like it ignores query parameters when doing a POST request to the token endpoint.

Of course we could parse the parameters from `TokenURL` and add them to the POST payload, but that seems a bit ugly to me.

About `Endpoint`: There currently is no such thing in the `clientcredentials` package.

**Comment by neelance** [comment]
@rakyll How can we proceed here? I can change the CL if you prefer some different solution.
