### ISSUE TITLE
it would be good to clearly indicate that this repo does not use pull requests

### ISSUE THREAD

**Issue by neelance** [golang/oauth2#217]
Imho it is not very obvious that this project does not use pull requests. It is probably not only me, because the main Go repo has 58 closed pull requests whereas this repo has 65. Wanting to contribute and then having the PR being closed by the bot is a frustrating experience. There is the `CONTRIBUTING.md` file, but I suggest adding two measures that the main Go repo uses:

1. Adding a section to the readme similar to the "Contributing" section of https://github.com/golang/go/#contributing, which states that pull requests are not used.
2. Open a dummy pull request similar to the one on https://github.com/golang/go/pulls.

**Comment by rakyll** [comment]
@bradfitz, how do we open a PR and make sure it is not auto-closed by the bot similar to https://github.com/golang/go/pull/9220?

**Comment by bradfitz** [comment]
I'm confused. Do you mean you want it to be auto-closed or not? It's already not, no?

**Comment by rakyll** [comment]
I want to open a PR against this repo as a reminder that we don't accept PRs (similar to golang/go#9220). I don't want it to be auto closed by the bot. How do I do that?

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/c/36914/.

**Comment by bradfitz** [comment]
Modify x/build/cmd/pushback perhaps? Or just let it be auto-closed and then re-open it?

**Comment by rakyll** [comment]
Reopening and locking worked, hope it won't be closed again by the bot in the future: https://github.com/golang/oauth2/pull/218.

**Comment by rakyll** [comment]
Oops, the bot closed it again: https://github.com/golang/oauth2/pull/218. I will create a CL against x/build/cmd/pushback at some point.
