### ISSUE TITLE
How to find out whether Token is refreshed and how to reach it?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [golang/oauth2#219]
I am going through the pkg oauth2 docs and trying to figure out when a token expires:

0. how can I know Token is refreshed
1. how can I get access to the refreshed Token instance (so that I can save it)

Sorry if the answer is obvious but I can't seem to understand it from godoc. So far I found these two:

```
func (c *Config) Client(ctx context.Context, t *Token) *http.Client
    Client returns an HTTP client using the provided token. The token will
    auto-refresh as necessary. The underlying HTTP transport will be
    obtained using the provided context. The returned client and its
    Transport should not be modified.
```

```
func (c *Config) TokenSource(ctx context.Context, t *Token) TokenSource
    TokenSource returns a TokenSource that returns t until t expires,
    automatically refreshing it as necessary using the provided context.
```

My guess is, when I use `config.Client(ctx, token)`, the `token` is replaced in-place, right?

But how do I know it’s changed so that I can persist it?

**Comment by rakyll** [comment]
Dup of https://github.com/golang/oauth2/issues/84, let's keep the convo there. We need a notifier mechanism.
