### ISSUE TITLE
Okta IDP needs to be added to brokenAuthHeaderProviders list

### ISSUE THREAD

**Issue by curtisallen** [golang/oauth2#224]
#### What version of Go are you using (go version)?
`go version go1.7.3 darwin/amd64`

#### What operating system and processor architecture are you using?
`macOS 10.12.1 darwin/amd64`

#### What did you do?
Attempt to use `oauth2.Exchange()` via [dex](https://github.com/coreos/dex/blob/master/connector/oidc/oidc.go)

#### What did you expect to see?
`internal.RetrieveToken` to return a Token when using [Okta](https://www.okta.com/) as an IDP

#### What did you see instead?
An error returned from Okta 
```console
401 Unauthorized
Response: 
{
  "error":"invalid_request",
  "error_description": "Cannot supply client credentials in both the Authentication header and the request-body."
}
```

#### Additional Context
It looks like Okta needs to be added to [brokenAuthHeaderProviders](https://github.com/golang/oauth2/blob/master/internal/token.go#L92) however Okta subdomains are dynamic per customer. e.g. https://dev-532085.oktapreview.com or https://dev-532085.okta.com https://[customer name].okta[preview].com

I'm happy to submit a PR, but it'll likely require a change to [providerAuthHeaderWorks](https://github.com/golang/oauth2/blob/master/internal/token.go#L139) to use `strings.Contains` 

cc:/ @ericchiang

**Comment by ericchiang** [comment]
@curtisallen you can do this through https://godoc.org/golang.org/x/oauth2#RegisterBrokenAuthHeaderProvider

**Comment by ericchiang** [comment]
This doesn't seem like an issue in golang.org/x/oauth2. Maybe open an issue on the dex issue tracker?

**Comment by curtisallen** [comment]
@ericchiang thanks, I'll open an issue on dex. I missed that func `RegisterBrokenAuthHeaderProvider`
