### ISSUE TITLE
google: provide DefaultTokenSourceFromJSON

### ISSUE THREAD

**Issue by adg** [golang/oauth2#225]
I have a JSON service account file downloaded from the Cloud Console and I'd like to be able to construct a default client based on its contents. With the code that's out there right now, I could do this:

```
                var d struct {
                        ClientEmail  string `json:"client_email"`
                        PrivateKeyID string `json:"private_key_id"`
                        PrivateKey   string `json:"private_key"`
                        TokenURL     string `json:"token_uri"`
                        ProjectID    string `json:"project_id"`
                }       
                if err := json.Unmarshal(b, &d); err != nil {
                        return err
                }                               
                cfg := &jwt.Config{                             
                        Email:        d.ClientEmail,
                        PrivateKey:   []byte(d.PrivateKey),
                        PrivateKeyID: d.PrivateKeyID,
                        Scopes:       []string{scope},
                        TokenURL:     d.TokenURL,
                }
                if cfg.TokenURL == "" {
                        cfg.TokenURL = google.JWTTokenURL
                }
                ctx := gContext.Background()
                client = oauth2.NewClient(ctx, cfg.TokenSource(ctx))
```

Or I could write the file somewhere and set the environment variable and then use the `google.DefaultClient` function.

Both of those approaches are messy, and I'd prefer to avoid this if I can.

@rakyll @bradfitz @broady what do you think about adding a `DefaultTokenSourceFromJSON` function?

**Comment by broady** [comment]
This is useful enough that we added it to our client library options:
https://godoc.org/google.golang.org/api/option#WithServiceAccountFile

-1 for the prefix "Default" - that should be reserved for ADC, which this is not.

But you don't need all of that code you wrote. Use the poorly named JWTConfigFromJSON function:
https://godoc.org/golang.org/x/oauth2/google#JWTConfigFromJSON

**Comment by adg** [comment]
> Use the poorly named JWTConfigFromJSON function:
https://godoc.org/golang.org/x/oauth2/google#JWTConfigFromJSON

I tried this initially but I got opaque permission errors. If you inspect the code, this doesn't do the same thing. That's how ended up here.  ☹️

**Comment by rakyll** [comment]
@adg, JWTConfigFromJSON internally depends on `google.credentialsFile` the same way the DefaultClient does. If you are depending on a service account for ADC, these two flows should work the same. I am happy to diagnose what's wrong if you need help.

**Comment by adg** [comment]
Ah my mistake, I was using `JWTAccessTokenSourceFromJSON` not `JWTConfigFromJSON`. Thanks for clearing up the confusion, and sorry for the noise.

**Comment by broady** [comment]
Another function like `TokenSourceFromJSON` would be useful - we can detect the type based on the JSON, just like we do for ADC.

**Comment by rakyll** [comment]
@broady, yup. credentialsFile already is capable of doing so but we don't export it.

TBH, this package is big, inconsistent and non-orthogonal now. I wished that we can break the APIs, we'd rename and reorg a few things.

**Comment by adg** [comment]
Maybe a series of scenarios in the package comment would help.

If you're running on a Compute instance, use X.
If you have a JSON file you downloaded from the console, use Y.
etc

**Comment by rakyll** [comment]
I will add more docs to navigate users better, thanks for the suggestion.
