### ISSUE TITLE
google: remove dependency to cloud.google.com/go/compute

### ISSUE THREAD

**Issue by rakyll** [golang/oauth2#227]
Duplicate the metadata package rather than  having a dependency to a large repo.

**Comment by esbie** [comment]
Heads up I ran into an issue with this while running `dep ensure`. 

My project imports `golang.org/x/oauth2` and `golang.org/x/oauth2/github`. dep vendors everything under oauth2 including /google (but then weirdly isn't vendoring `cloud.google.com/go/compute` and its many many dependencies).

**Comment by bradfitz** [comment]
I think this bug is probably obsolete. The Go modules tooling should be able to handle this all. (If not today, soon enough.)

Let me know if you disagree.
