### ISSUE TITLE
Missing last step with Amazon Login

### ISSUE THREAD

**Issue by zxcvbn4038** [golang/oauth2#228]
I've got almost everything working with Amazon login, the config looks like this:

conf = &oauth2.Config{
  ClientID:     "AMAZON-CLIENT-ID",
  ClientSecret: "AMAZON-CLIENT-SECRET",
  RedirectURL:  "https://...",
  Scopes:       []string{"profile"},
  Endpoint: oauth2.Endpoint{
    AuthURL:  "https://www.amazon.com/ap/oa",
    TokenURL: "https://api.amazon.com/auth/O2/tokeninf",
   },
}

It makes it all the way through to my callback, I'm able to verify the code.

The last step is to retrieve the user profile:

resp, err := client.Get("https://api.amazon.com/user/profile")

But I get the following error:

```
Bad Request: oauth2: cannot fetch token: 404 Not Found
Response: <UnknownOperationException/>
```

The address I am supposed to be hitting is:

https://api.amazon.com/user/profile?access_token=<session_token>

However, I'm not clear if the access_token= is something that golang/x/oauth provides or is something I need to provide. I don't see an easy way to insert an DumpRequest() to see what the module is sending.

As an alternative I can leave off the access_token= and pass the token in an "x-amz-access-token" header. 

I could use some advice on the best way to proceed.

**Comment by zxcvbn4038** [comment]
Reading through again it also looks like the header:

```
Authorization: Bearer <session_token>
```

Is also a supported method. [Developer Docs, pg 34](https://images-na.ssl-images-amazon.com/images/G/01/lwa/dev/docs/website-developer-guide._TTH_.pdf)

**Comment by rakyll** [comment]
It seems like you are failing to retrieve a token before hitting the user profile. Where did you get the AuthURL and TokenURL?

**Comment by rakyll** [comment]
Never mind, there are in the developer docs you have just linked.

**Comment by rakyll** [comment]
Could you try the following? You are using the wrong token URL.

```
conf = &oauth2.Config{
ClientID: "AMAZON-CLIENT-ID",
ClientSecret: "AMAZON-CLIENT-SECRET",
RedirectURL: "https://...",
Scopes: []string{"profile"},
Endpoint: oauth2.Endpoint{
AuthURL: "https://www.amazon.com/ap/oa",
TokenURL: "https://api.amazon.com/auth/o2/token",
},
}
```

**Comment by zxcvbn4038** [comment]
@rakyll That was it, sharp eye spotting the typeo in TokenURL, everything works with it corrected. Thank you for the help!

**Comment by rakyll** [comment]
Closed via https://github.com/golang/oauth2/commit/a6bd8cefa1811bd24b86f8902872e4e8225f74c4.
