### ISSUE TITLE
Oauth2: Support for providing scopes during Refresh token flow.

### ISSUE THREAD

**Issue by bwplotka** [golang/oauth2#234]
Hi, It is often required to provide scopes for refresh token flow. However I cannot pass any additional `url.Values` for `TokenSource.Token` https://github.com/golang/oauth2/blob/master/oauth2.go#L232

Is there any reason why `oauth2.Token()` method does not allow to provide that optional parameter? See: https://tools.ietf.org/html/rfc6749#section-6

What do you think about such change?
```
tk, err := retrieveToken(tf.ctx, tf.conf, url.Values{
                "grant_type":    {"refresh_token"},
                "refresh_token": {tf.refreshToken},
+++             "scope":      internal.CondVal(strings.Join(tf.conf.Scopes, " ")),
})
```

How can I workaround that if the above change is not possible?

Thanks!

**Comment by zombiezen** [comment]
What value are you attempting to put in `scope` for a `refresh_token` request?  I might be able to add this in, but I'd like to understand how it's used.

**Comment by bwplotka** [comment]
Wow, quite an old issue (: Someone shared this one to me just now. Let's close this as it's no longer blocking me. In short, because I could not fix this and I think other blockers, I created my own lib: https://github.com/bwplotka/oidc 

I don't remember anymore, but I think the use case is to be compatible with Oauth2 RFC (and OIDC in same time)
