### ISSUE TITLE
Cannot acquire token with LINE Login

### ISSUE THREAD

**Issue by k2wanko** [golang/oauth2#236]
Token could not be acquired with error like the following.

I have fix code.
please check.

https://go-review.googlesource.com/c/44410/

```bash
$ go version
go version go1.8.3 darwin/amd64

$ go run main.go
Visit the URL for the auth dialog: https://access.line.me/dialog/oauth/weblogin?client_id=LINE_CLIENT_ID&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth%2Fcallback&response_type=code&state=state
2017/06/13 13:01:21 Exchange Error: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_request","error_description":"some parameters missed or invalid"}
```

```go
package main

import (
	"context"
	"fmt"
	"log"

	"net/http"

	"io"

	"golang.org/x/oauth2"
)

func main() {
	ctx := context.Background()
	ctx, cancel := context.WithCancel(ctx)
	conf := &oauth2.Config{
		ClientID:     "LINE_CLIENT_ID",
		ClientSecret: "LINE_CLIENT_SECRET",
		Endpoint: oauth2.Endpoint{
			AuthURL:  "https://access.line.me/dialog/oauth/weblogin",
			TokenURL: "https://api.line.me/v2/oauth/accessToken",
		},
		RedirectURL: "http://localhost:8080/oauth/callback",
	}

	go func() {
		http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                        defer cancel()
			if r.URL.Path != "/oauth/callback" {
				http.NotFound(w, r)
				return
			}

			code := r.URL.Query().Get("code")
			if code == "" {
				http.Error(w, "Not code", 400)
				return
			}
			tok, err := conf.Exchange(ctx, code)
			if err != nil {
				log.Printf("Exchange Error: %v", err)
				http.Error(w, err.Error(), 500)
				return
			}

			hc := conf.Client(ctx, tok)
			resp, err := hc.Get("https://api.line.me/v2/profile")
			if err != nil {
				log.Printf("Get profile Error: %v", err)
				http.Error(w, err.Error(), 500)
				return
			}
			log.Printf("Token: %v", tok)
			io.Copy(w, resp.Body)
		})
		http.ListenAndServe(":8080", nil)
	}()

	url := conf.AuthCodeURL("state")
	fmt.Printf("Visit the URL for the auth dialog: %v\n", url)
	<-ctx.Done()
}
```

**Comment by szqmtl** [comment]
I tried LINE service with end point:
oauth2.Endpoint{
	AuthURL:  "https://access.line.me/oauth2/v2.1/authorize",
	TokenURL: "https://api.line.me/oauth2/v2.1/token",
} and Scopes: []string{
				"profile",
			},
and profile url: https://api.line.me/v2/profile

It works.

Hope it helps.

**Comment by Azraels** [comment]
I tried the same method with @szqmtl , 
but when i get profile, 
always response invalid token. 

I implement with php curl, 
can someone help me?

**Comment by szqmtl** [comment]
@Azraels have you looked into the way you set the token?

**Comment by Azraels** [comment]
Hi @szqmtl , the setting as follows:

<pre>
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://api.line.me/v2/profile');
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Authorization: Bearer {'.$accessToken.'}'));
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$profile = curl_exec($ch);
</pre>

and get response:
<pre>
{"message":"invalid token"}
</pre>

**Comment by szqmtl** [comment]
@Azraels I don't have so much experience with php curl, I couldn't help you further, but I would suggest:
1. making sure the value of accessToken is corrected.
2. testing all parameters with command line tool curl.
3. debugging what the php curl sends comparing to the corrected value of curl.

**Comment by bradfitz** [comment]
This looks like it was resolved, or timed out.
