### ISSUE TITLE
Supporting standard lib context

### ISSUE THREAD

**Issue by marcsantiago** [golang/oauth2#246]
For some projects I have to import `context` as well as `oldContext "golang.org/x/net/context"`

**Comment by rakyll** [comment]
We unfortunately are still supporting 1.6 because a few critical libraries are stuck there. Why can't you just import context and pass it? context.Context satisfies "golang.org/x/net/context".Context.

**Comment by drywheat** [comment]
**Go version:** v1.10.2

Regardless of the `import` statement, it still requires developers to add `golang.org/x/net/context` as a dependency to whichever package manger (dep, Glide, etc...) they're using othewise the project will not build on a fresh workstation.

Is there a timeline for this change or at least an EOL deadline for v1.6?

**Comment by bradfitz** [comment]
It'll probably be another 6 months. Sorry. I'm frustrated by it too.

**Comment by drywheat** [comment]
No worries, thanks for the swift response.  I'll just watch and wait until then.

**Comment by bradfitz** [comment]
We can submit this tomorrow morning.
