### ISSUE TITLE
Foursquare not accept Authorization header token

### ISSUE THREAD

**Issue by acomagu** [golang/oauth2#252]
I'm trying Foursquare API and it fails.
## What version of Go are you using (go version)?
Go 1.9.1
## What operating system and processor architecture are you using?
linux/amd64
## What did you do?
I tried Foursquare API with a bit code:
```
client := config.Client(oauth2.NoContext, token)
resp, err := client.Get("https://api.foursquare.com/v2/users/self/friends")
```

It can be reproduced with curl:
```
 ❯❯ curl -H "Authorization: Bearer $TOKEN" 'https://api.foursquare.com/v2/users/self/checkins?v=20170430'
{"meta":{"code":400,"errorType":"invalid_auth","errorDetail":"Missing access credentials. See https:\/\/developer.foursquare.com\/docs\/oauth.html for
 details.","requestId":"59e55dde4434b93bf84131b0"},"response":{}}
```

The token is valid because give token as URI parameter and it success.

```
 ❯❯ curl "https://api.foursquare.com/v2/users/self/checkins?oauth_token=$TOKEN&v=20170430"
{"meta":{"code":200,"requestId":"59e517b7dd579764e68d7b9f"},"notifications":[{"type":"notificationTray","item":{"unreadCount":11}}],"response":{"check...
```

## What did you expect to see?
JSON includes friend list.
```
{"meta":{"code":200,"requestId":"59e55db21ed2196849312671"},"notific...
```

## What did you see instead?
Error response "Missing access credentials".
```
{"meta":{"code":400,"errorType":"invalid_auth","errorDetail":"Missing access credentials. See https:\/\/developer.foursquare.com\/docs\/oauth.html for
 details.","requestId":"59e55dde4434b93bf84131b0"},"response":{}}
```

I mean, the Foursquare API Authorization is assumed broken, and this library should put authorization token as query parameter if the target is Foursquare?

Thanks.

**Comment by bradfitz** [comment]
This is now automatic as of https://github.com/golang/oauth2/commit/80673b4a4bfc6c2c58a0b44cf9106913fe293994
