### ISSUE TITLE
unrecognized import path

### ISSUE THREAD

**Issue by engr-Eghbali** [golang/oauth2#254]
**function used:**
`go get golang.org/x/oauth2/google`
**expect:**
download package
**what happened?**
`
package cloud.google.com/go/compute/metadata: unrecognized import path "cloud.google.com/go/compute/metadata" (parsing cloud.google.com/go/compute/metadata: XML syntax error on line 9: expected /> in element)
`
**thanks for helping**

**Comment by engr-Eghbali** [comment]
OH god!
seems like serving repository from that path is missing, I find the repository in github and clone it into my $GOPATH/src then Move the container of project to go.

**Comment by zombiezen** [comment]
I attempted to reproduce using the following:

```
$ go version
go version go1.9 darwin/amd64
$ mkdir ~/Desktop/foo
$ GOPATH=$HOME/Desktop/foo go get golang.org/x/oauth2/google
```

And I could not see the failure you described.  I inspected the HTML at https://cloud.google.com/go/compute/metadata and could not see fault.

@engr-Eghbali Did you use vanilla `go get` or another dep management tool?  I've encountered similar failures on a different Go repository when a user was using gvt (see FiloSottile/gvt#31).

**Comment by engr-Eghbali** [comment]
@zombiezen No I did not...
But I just understood it might becaused of google sanctions in some countries,(just see 403 error on 
https://cloud.google.com/go/compute/metadata )
whats your idea?
(thanks to cooperating with me,god damn governments!)

**Comment by andybons** [comment]
Hi @engr-Eghbali! Can you paste the output of

```sh
curl -i https://cloud.google.com/go/compute/metadata/
```

Thanks

**Comment by engr-Eghbali** [comment]
@andybons sure...

`HTTP/1.1 403 Forbidden
Content-Type: text/html; charset=UTF-8
Referrer-Policy: no-referrer
Content-Length: 1599
Date: Mon, 30 Oct 2017 17:24:49 GMT
Alt-Svc: quic=":443"; ma=2592000; v="41,39,38,37,35"

<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/go/compute/metadata/</code> from this server.  <ins>That’s all we know.</ins>
`

**Comment by manhtai** [comment]
Same issue here

Try

```
go get -u cloud.google.com/go/compute/metadata
```

solves my problem.

**Comment by engr-Eghbali** [comment]
I think it's can't be open anymore...

**Comment by andybut** [comment]
Hey. I have these problem in 2024)
root@user:~/monitoring/cadvisor# go get -u cloud.google.com/go/compute/metadata
go: unrecognized import path "cloud.google.com/go/compute/metadata": reading https://cloud.google.com/go/compute/metadata?go-get=1: 403 Forbidden

**Comment by andybut** [comment]
root@user:~/monitoring/cadvisor# curl -i https://cloud.google.com/go/compute/metadata/
HTTP/2 403
content-type: text/html; charset=UTF-8
referrer-policy: no-referrer
content-length: 1599
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png)
0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png)
no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/go/compute/metadata/</code> from this server.  <ins>That’s all we know.</ins>
root@user:~/monitoring/cadvisor#
