### ISSUE TITLE
Cloud Spanner and AppEngine Authentication failure

### ISSUE THREAD

**Issue by clanstyles** [golang/oauth2#260]
Cloud Spanner is requiring you to set the context and the database credentials. If you run it in AppEngine, it ends up hitting this chunk of code in oauth2.

https://github.com/golang/oauth2/blob/master/google/default.go#L90
```
	// Third, if we're on Google App Engine use those credentials.
	if appengineTokenFunc != nil && !appengineFlex {
		return &DefaultCredentials{
			ProjectID:   appengineAppIDFunc(ctx),
			TokenSource: AppEngineTokenSource(ctx, scope...),
		}, nil
	}
```

This code seems to "break" their auth system in Cloud Spanner + AppEngine.

See https://github.com/GoogleCloudPlatform/google-cloud-go/issues/829

**Comment by zombiezen** [comment]
This is working as intended, I've answered on the other issue.
