### ISSUE TITLE
`jwt.Config` should allow private claims

### ISSUE THREAD

**Issue by kryzthov** [golang/oauth2#266]
To generate a Google ID token, we need to emit a JWT token with a `target_audience` claim that will be used as the audience claim in the resulting ID token.

We could introduce `jwt.Config.PrivateClaims` to configure `jws.ClaimSet.PrivateClaims` accordingly. 

Creating a source of Google ID tokens would look like:
```
cfg, err := google.JWTConfigFromJSON(...)  // initialize from service account key
jwtConfig := &jwt.Config{
		Email:         cfg.Email,
		PrivateKey:    cfg.PrivateKey,
		TokenURL:      "https://www.googleapis.com/oauth2/v4/token",
		Subject:       cfg.Email,
		PrivateClaims: map[string]interface{}{"target_audience": *audience},
}
source := jwtConfig.TokenSource(ctx)
```

and retrieving a new ID token would look like:
```
token, err := source.Token()
idToken := token.Extra("id_token").(string)
```

In order to use the Token as Bearer token, we might also need to set `token.AccessToken = idToken`.

**Comment by dmitshur** [comment]
I believe this has been resolved via [CL 166220](https://golang.org/cl/166220). /cc @wlhee @bradfitz
