### ISSUE TITLE
Add https://api.medium.com/v1/tokens to the list of brokenAuthHeaderProviders

### ISSUE THREAD

**Issue by aweisser** [golang/oauth2#267]
The auth provider `api.medium.com` does not seem to implement the OAuth2 spec fully.
When I try to authenticate the internal Post request returns an error:

```
Error: oAuth exchanged failed: oauth2: cannot fetch token: 400 Bad Request
Response: {"errors":[{"message":"No client_id specified.","code":6014}]}
```

When I add `https://api.medium.com/v1/tokens` to the list of `brokenAuthHeaderProviders` in package `golang.org/x/oauth2/internal` everything works fine.

**Comment by FenwickElliott** [comment]
If you'd just like someone to add that url to the string slice on golang.org/x/oauth2/internal/token.go and submit the commit I'd be more than happy to.

Let me know,

**Comment by cnbuff410** [comment]
Hi @FenwickElliott, if you can help to add 

`https://log.finalsurge.com/oauth/token`

to the string slice there, that would be greatly appreciated. Thanks! I don't have the Gerrit installed.

**Comment by cnbuff410** [comment]
Hi @FenwickElliott, do you have time to also add

`https://multisport.todaysplan.com.au/rest/oauth/access_token` and `https://whats.todaysplan.com.au/rest/oauth/access_token`

to the string slice?

**Comment by FenwickElliott** [comment]
@cnbuff410 

I've submitted the change. I'll let you know when it's been accepted.


Thanks,

C

**Comment by cnbuff410** [comment]
Hi @FenwickElliott, generally how long does it take for the change to merge?

**Comment by bradfitz** [comment]
@cnbuff410, I just merged it. It slipped through the cracks.
