### ISSUE TITLE
Add https://stackexchange.com/oauth/access_token to the list of brokenAuthHeaderProviders

### ISSUE THREAD

**Issue by aweisser** [golang/oauth2#268]
The auth provider `stackexchange.com` does not seem to implement the OAuth2 spec fully.
When I try to authenticate the internal Post request returns an error:

```
Error: oAuth exchanged failed: oauth2: cannot fetch token: 400 Bad Request
Response: {"errors":[{"message":"No client_id specified.","code":6014}]}
```

When I add https://stackexchange.com/oauth/access_token` to the list of `brokenAuthHeaderProviders` in package `golang.org/x/oauth2/internal` everything works fine.

**Comment by FenwickElliott** [comment]
If you'd just like someone to add that url to the string slice on golang.org/x/oauth2/internal/token.go and submit the commit I'd be more than happy to.

Let me know,
