### ISSUE TITLE
Why storing requests in Transport RoundTripper

### ISSUE THREAD

**Issue by yashpal1995** [golang/oauth2#271]
I'm quite new to golang, want to know why this lib stores the modified requests in [modReq map](https://github.com/golang/oauth2/blob/master/transport.go#L30) and later delete it after finishing the base roundtripper or closing body. Is this because to support CancelRequest for previous golang version? Won't there be little performance issue as the map is protected with mutex? Why not simply add the authorization header to the request.

**Comment by bradfitz** [comment]
> Is this because to support CancelRequest for previous golang version?

Probably. I think it's probably time to delete that old code and remove the CancelRequest method.
