### ISSUE TITLE
`client_id` required in URL parameters as per RFC 6749

### ISSUE THREAD

**Issue by Lepthy** [golang/oauth2#275]
Our oauth2 provider recently moved to enforce this RFC and it seem this library doesn't pass on the client_id.

Did I miss something obvious? We pass the client_id when creating the Oauth2Config struct.

Line error:
https://github.com/golang/oauth2/blob/b28fcf2b08a19742b43084fb40ab78ac6c3d8067/oauth2.go#L188

RFC:
https://tools.ietf.org/html/rfc6749#section-4.1.3

This might be related to: https://github.com/golang/oauth2/issues/268

**Comment by bradfitz** [comment]
Keep following the code. It eventually calls this:

https://github.com/golang/oauth2/blob/b28fcf2b08a19742b43084fb40ab78ac6c3d8067/internal/token.go#L172

```go
func RetrieveToken(ctx context.Context, clientID, clientSecret, tokenURL string, v url.Values) (*Token, error) {
	bustedAuth := !providerAuthHeaderWorks(tokenURL)
	if bustedAuth {
		if clientID != "" {
			v.Set("client_id", clientID)
		}
		if clientSecret != "" {
			v.Set("client_secret", clientSecret)
		}
	}
```

**Comment by Lepthy** [comment]
If i'm reading this correctly it assumes passing it in the URL is wrong and therefore we should modify this `brokenAuthHeaderDomains` variable, but according to the RFC they are required to be passed by URL parameters: 

```
  The client makes a request to the token endpoint by sending the
   following parameters using the "application/x-www-form-urlencoded"
   format per Appendix B with a character encoding of UTF-8 in the HTTP
   request entity-body:

   grant_type
         REQUIRED.  Value MUST be set to "authorization_code".

   code
         REQUIRED.  The authorization code received from the
         authorization server.

   redirect_uri
         REQUIRED, if the "redirect_uri" parameter was included in the
         authorization request as described in Section 4.1.1, and their
         values MUST be identical.

   client_id
         REQUIRED, if the client is not authenticating with the
         authorization server as described in Section 3.2.1.
```

Shouldn't it be the other way around then? Or is another RFC used?

**Comment by bradfitz** [comment]
Our whole `brokenAuthHeaderDomains` list only exists because some OAuth2 servers only speak one variant, and other servers only speak another variant. If there was one way that worked for everyone, that'd be awesome. (And extra awesome if the RFC said that was the correct way).

Honestly I forget most of the OAuth2 RFC at this point.

But if you want to remove that `brokenAuthHeaderDomains` crap and clean up our OAuth2 code to always do the same thing to everybody, we'd love it, assuming it works. You'd need to test it too.

**Comment by Lepthy** [comment]
I can take a look and come back to you here, in the meantime I will add this fix as it's disrupting our application.
Please do not close this issue yet.
