### ISSUE TITLE
Expose RetrieveError from internal package

### ISSUE THREAD

**Issue by fabotronix** [golang/oauth2#277]
It would be nice to have the [RetrieveError type](https://github.com/golang/oauth2/blob/fdc9e635145ae97e6c2cb777c48305600cf515cb/internal/token.go#L259) exposed. Currently it is inside an "internal" package and the body of the original response is therefore not accessible.

Handling special error codes is therefore currently only possible by parsing the error message.

**Comment by bontibon** [comment]
All instances of internal.RetrieveError already get converted to [oauth2.RetrieveError](https://github.com/golang/oauth2/blob/master/token.go#L166). Have you found an instance where this is not the case?

**Comment by fabotronix** [comment]
Sorry, I tested it with an older version and overlooked that the error is now converted.
