### ISSUE TITLE
Int overflow in tokenJSON.ExpirationTime (casting int64 to int32)

### ISSUE THREAD

**Issue by j3ch** [golang/oauth2#279]
TokenJSON expirationTime is typed to int32. The unmarshal code further cast int64 to int32

expirationTime should just be int64. 

This is an issue when some apps return really long expiration time to indicate permanent tokens, causing int overflow.

**Comment by bradfitz** [comment]
@rakyll, do you remember why it's like that?

Currently the code is:

```go
type tokenJSON struct {
        AccessToken  string         `json:"access_token"`
        TokenType    string         `json:"token_type"`
        RefreshToken string         `json:"refresh_token"`
        ExpiresIn    expirationTime `json:"expires_in"` // at least PayPal returns string, while most return number                                  
        Expires      expirationTime `json:"expires"`    // broken Facebook spelling of expires_in                                                    
}

type expirationTime int32

func (e *expirationTime) UnmarshalJSON(b []byte) error {
        var n json.Number
        err := json.Unmarshal(b, &n)
        if err != nil {
                return err
        }
        i, err := n.Int64()
        if err != nil {
                return err
        }
        *e = expirationTime(i)
        return nil
}
```

**Comment by bradfitz** [comment]
expires_in doesn't have a defined size in https://tools.ietf.org/html/rfc6749#section-4.2.2 , and JavaScript can't do 64-bit ints, which is probably why it's int32.

But we can detect the overflow and cap it at MaxInt32 instead.

**Comment by bradfitz** [comment]
https://go-review.googlesource.com/c/oauth2/+/161962
