### ISSUE TITLE
invalid_grant

### ISSUE THREAD

**Issue by leefernandes** [golang/oauth2#28]
Using the same credentials & .pem that are working in other googleapi libraries with example_test.go Example_jWTConfig, I am getting "invalid_grant", and "Cannot fetch token, response: 400 Bad Request" errors.

The only things I'm not 100% confident about are how the PrivateKey is meant to be passed, and what audURL is expected to be.  I'm currently reading the .pem w/ ioutil, assigning the []byte result of that to the JWTOptions.PrivateKey, and passing "https://accounts.google.com/o/oauth2/token" as the aud argument.

**Comment by taalhach** [comment]
i was getting 
```
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
}.
```
i used to get auth code from frotend and used that code to retrieve access token and refresh token while i was setting up i had no redirect uris and it worked fine with localhost domains but as soon as code was deployed to staging server i started getting invalid_grant bad request error. 

i spent hours in debugging and came to know when there is no redirect_uri and domain urls are not localhost then redirect_uri must be specified to postmessage. i have configs like this 
```
configs := oauth2.Config{
		ClientID:     CLIENT_ID,
		ClientSecret: CLIENT_SECRET,
		Endpoint:     google.Endpoint,
		Scopes:       []string{"https://www.googleapis.com/auth/userinfo.profile", "https://www.googleapis.com/auth/userinfo.email"},
		RedirectURL:  "postmessage",
	} 
```
this solved my issue i hope it will help someone else
