### ISSUE TITLE
Allow override of `grant_type` in `client_credentials`

### ISSUE THREAD

**Issue by ismith** [golang/oauth2#283]
RFC6749 4.2.2 specifies that `grant_type` "MUST be set to "client_credentials"."; as a result of this, the `clientcredentials` package does not allow `grant_type` to be overwritten (https://github.com/golang/oauth2/blob/master/clientcredentials/clientcredentials.go#L91).

It'd be nice to be able to override this, though, to allow working with non-compliant implementations.  Would changing that check to warn instead of returning an error be objectionable?

**Comment by bradfitz** [comment]
Which non-compliant implementations, and how are they non-compliant?

Are there upstream bug reports?

**Comment by ismith** [comment]
`apigatewayb2b.qa.bnymellon.com`/`apigatewayb2b.bnymellon.com`:
- requires a client cert
- requires Basic Auth creds - both `client_Id` and `client_secret`
- requires `grant_type=client_cert`.
- returns json containing keys `access_token`,`scope`,`token_type`,`expires_in`

(Their documentation provides as an example: `curl -k -d "grant_type=client_cert" --basic -u "{consumer key}:{consumer secret}" -H "Content-Type: application/x-www-form-urlencoded" --cert {Certificate Pem} https://apigatewayb2b.bnymellon.com/token`)

Note that this is not https://tools.ietf.org/html/draft-ietf-oauth-mtls-04 (the returned json does not match that document, and that document does not specify basic auth).

Using the `clientcredentials` package with the `"oauth2: cannot overwrite parameter %q"` error removed, and a `clientcredentials.Config` containing `EndpointParams: url.Values{"grant_type": []string{"client_cert"}},` and appropriate values for `TokenURL`, `ClientID`, and `ClientSecret`, I receive a token and can successfully use it to make further requests to the API.  (That is, it's using the two-legged OAuth 2.0 flow.)
