### ISSUE TITLE
Transition from cloud.google.com/go to google.golang.org/cloud

### ISSUE THREAD

**Issue by ingvagabund** [golang/oauth2#284]
commit: `cdc340f7c179dbbfa4afd43b7614e8fcadde4269`

```sh
$ grep -rn "cloud.google.com"
google/sdk.go:53:// The Google Cloud SDK is available at https://cloud.google.com/sdk/.
google/default.go:16:	"cloud.google.com/go/compute/metadata"
google/google.go:14:	"cloud.google.com/go/compute/metadata"
google/google.go:154:// server can be found at https://cloud.google.com/compute/docs/authentication.
```

The are still some files that import `cloud.google.com/go/compute/metadata`. Is there anything stopping the project from changing the package to `google.golang.org/cloud/compute/metadata`?

**Comment by bradfitz** [comment]
Google.golang.org/cloud was the OLD import path. We migrated some years ago.

Do you will see the old import paths anywhere?

**Comment by ingvagabund** [comment]
Oh, my bad. For some reason I though the `google.golang.org/cloud` is the new one.
