### ISSUE TITLE
oauth2,internal: stale link to busted auth header providers issue

### ISSUE THREAD

**Issue by kortschak** [golang/oauth2#287]
In oauth2.go and internal/token.go there are link to explanatory text for `RegisterBrokenAuthHeaderProvider` and `providerAuthHeaderWorks`, pointing to https://code.google.com/p/goauth2/issues/detail?id=31. This link no longer works. This may be a problem with the googlecode archive since no search functionality seems to work there anymore either.

**Comment by bradfitz** [comment]
That link works for me right now.

I see:

> Posted on Feb 3, 2014 by Grumpy Cat
> Reddit's Oauth implementation requires a basic HTTP auth header containing the ClientId & ClientSecret values to be included when a token is requested.
>
> It would be great if goauth2 supported this.

And then 13 comments.

**Comment by kortschak** [comment]
Ah, sorry. uMatrix strikes!
