### ISSUE TITLE
compilation fails on go 1.10.1

### ISSUE THREAD

**Issue by shmul** [golang/oauth2#296]
Hi,

When trying to build the package using go 1.10.1 (Ubuntu 16.04), I get the following errors
```
not_go19.go:17: DefaultCredentials redeclared in this block
        previous declaration at default.go:24
not_go19.go:42: FindDefaultCredentials redeclared in this block
        previous declaration at default.go:70
not_go19.go:43: undefined: findDefaultCredentials
not_go19.go:53: undefined: credentialsFromJSON
```
Perhaps the build tag should be extended?

Cheers,
Shmul

**Comment by bradfitz** [comment]
I can't reproduce. I'm able to build it with Go 1.8, Go 1.9, Go 1.10, and Go tip.

Also, there is no `default.go` file. I think your git checkout is in a weird state.

Nuke it and re-fetch if you can't reset it back to master.

**Comment by bradfitz** [comment]
Oh, you meant the x/oauth2/google package. I see the `default.go` file there, but I still can't reproduce. It builds fine for me on all Go versions.
