### ISSUE TITLE
oauth token expired function

### ISSUE THREAD

**Issue by 1stdropshipping** [golang/oauth2#302]
hi look below function

// expired reports whether the token is expired.
// t must be non-nil.
func (t *Token) expired() bool {
        if t.Expiry.IsZero() {
                return false
        }
        return t.Expiry.Round(0).Add(-expiryDelta).Before(time.Now())
}

shouldn't this function return true if token expired? 
or if u made it return false for expired then the function Valid need to be changed 

// Valid reports whether t is non-nil, has an AccessToken, and is not expired.
func (t *Token) Valid() bool {
        return t != nil && t.AccessToken != "" && !t.expired()
}

**Comment by 1stdropshipping** [comment]
it currently returns **false** if the token expired
func expired
if t.Expiry.IsZero() --> should return **true**

t.Expiry.Round(0).Add(-expiryDelta).Before(time.Now()) ---> should be ! t.Expiry.Round(0).Add(-expiryDelta).Before(time.Now())

so if the expiry is older than current time then it should return true, not t.Expiry.Round(0).Add(-expiryDelta).Before(time.Now()),  this will return false 

The token auto refresh doesn't work until i made the function to  below

func (t *Token) expired() bool {
        if t.Expiry.IsZero() {
                return true
        }
        return ! t.Expiry.Round(0).Add(-expiryDelta).Before(time.Now())
}

**Comment by bontibon** [comment]
It sounds like the OAuth2 authorization server you are using could be implemented incorrectly.

**Comment by 1stdropshipping** [comment]
it is gmail api for Go 
I still think it is these two function's problem especially expired()
it should return true if it is expired 
and false if it is not expired

you are returning false on expired
true on not expired

**Comment by maks56893** [comment]
Faced with same issue. OAuth2 server returned number of seconds, for example 1 month in seconds, and to get expiry date i add 1 month to time now. In this case func expired will return false and token will refresh, but it not really expired. I think this func should be inverted or use after instead before
