### ISSUE TITLE
Getting Email from a Google OAuth ID Token with Golang

### ISSUE THREAD

**Issue by Tsmith18256** [golang/oauth2#306]
I am following the guide at https://developers.google.com/identity/sign-in/android/backend-auth to get OAuth working with my Android app. I have successfully managed to get the ID token and send it to the server, but now I can't get the next step completed with Golang.

How do I simply take this ID token and get the email address from it so that I can log the user in on my server? Any guides and documentation I can find on this are either doing things completely different, referencing an old version of the oauth APIs, or seem to be using a pattern that only works for web. I can't believe it is this hard to get Google sign in working with Google's language.

**Comment by fstanis** [comment]
Per https://accounts.google.com/.well-known/openid-configuration, the `userinfo_endpoint` for Google is https://www.googleapis.com/oauth2/v3/userinfo so all you need to is send a GET request to that URL with a correct access token.

The code I use for that is this (where `*http.Client` is what you get from the [Client](https://godoc.org/golang.org/x/oauth2#Config.Client) method in `oauth2.Config`):

```go
type UserInfo struct {
	Sub           string `json:"sub"`
	Name          string `json:"name"`
	GivenName     string `json:"given_name"`
	FamilyName    string `json:"family_name"`
	Profile       string `json:"profile"`
	Picture       string `json:"picture"`
	Email         string `json:"email"`
	EmailVerified bool   `json:"email_verified"`
	Gender        string `json:"gender"`
}

func FetchUserInfo(client *http.Client) (*UserInfo, error) {
	resp, err := client.Get("https://www.googleapis.com/oauth2/v3/userinfo")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	data, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	var result UserInfo
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}
	return &result, nil
}
```
