### ISSUE TITLE
Add `UserInfoURL` to oauth2.Endpoint

### ISSUE THREAD

**Issue by fstanis** [golang/oauth2#307]
(apologies if this came up before, couldn't find any relevant issue)

Since getting the information about the user from the OpenID UserInfo Endpoint is a common use-case, would it make sense to add this URL to `oauth2.Endpoint`?

```diff
// Endpoint contains the OAuth 2.0 provider's authorization and token
// endpoint URLs.
type Endpoint struct {
	AuthURL     string
	TokenURL    string
+	UserInfoURL string
}
```

In addition, incorporating the `UserInfo` struct like the one from [my previous comment](https://github.com/golang/oauth2/issues/306#issuecomment-408622439) might be useful, e.g. `oauth2.UserInfo`. I'd also add some form of the `FetchUserInfo` function from the same comment which would automatically use `UserInfoURL` from the `Endpoint`, but not quite sure where this might fit into the API?

Happy to send a PR - just wanted to bring this up for discussion first. Thoughts?

**Comment by bontibon** [comment]
Seems like something that should be discovered dynamically by fetching `/.well-known/openid-configuration`.

**Comment by fstanis** [comment]
> That would make it out of scope of the package.

Fair, though perhaps we can have `golang/oauth2/oidc` or so for this?

I'm not strongly opinionated about it, but it [seems common for people to re-define this struct](https://github.com/search?l=Go&q=sub+name+given_name+family_name&type=Code) in their code, so I feel it's a good candidate to be part of this library.

> Seems like something that should be discovered dynamically by fetching `/.well-known/openid-configuration`.

I actually think it'd be a good idea to have some static generator for files like [paypal.go](https://github.com/golang/oauth2/blob/master/paypal/paypal.go) that pull AuthURL (authorization_endpoint) and TokenURL (token_endpoint) from (in this case) https://www.paypal.com/.well-known/openid-configuration (when available) - but that's probably worth having as a separate issue.

Or alternatively just have the dynamic logic for `/.well-known/openid-configuration` in the aforementioned `golang/oauth2/oidc` if we go with that.

**Comment by bradfitz** [comment]
I don't think we want to maintain more packages in golang.org/x/oauth2/..., so I'd encourage the creation of an oidc package elsewhere.
