### ISSUE TITLE
Use new endpoints for Google authentication

### ISSUE THREAD

**Issue by JustinBeckwith** [golang/oauth2#310]
[Parent issue](https://github.com/GoogleCloudPlatform/google-cloud-common/issues/260)

The following specific library changes are required:

### OAuth 2.0 Authorization Grant Flow (aka 3LO)

For clients using this flow, change (and test):
- https://accounts.google.com/o/oauth2/token -> https://oauth2.googleapis.com/token
- https://accounts.google.com/o/oauth2/revoke -> https://oauth2.googleapis.com/revoke
- https://accounts.google.com/o/oauth2/tokeninfo -> https://oauth2.googleapis.com/tokeninfo
- *DO NOT* change https://accounts.google.com/o/oauth2/auth

If the client pulls the data from the client json object, that will be updated on the server side for newly created clients and no changes to the client libraries are required.

### OAuth 2.0 Assertion Flow (aka OAuth 2.0 Service Account Flow, aka “Google Credentials Auth”)

For clients using these flows, change:
- https://accounts.google.com/o/oauth2/token -> https://oauth2.googleapis.com/token
- The “audience” of the token from https://accounts.google.com/o/oauth2/token ->  https://oauth2.googleapis.com/token

### JWT Bearer

No changes should be required for JWT Bearer authentication

### ODIC Identity Tokens

There are two options.  If possible, the preferred option in this case is to:
- Change https://accounts.google.com/o/oauth2/token ->  https://oauth2.googleapis.com/token
- Change audience verification from “accounts.google.com” to [“accounts.google.com”, “https://accounts.google.com”]
- *DO NOT* Change https://www.googleapis.com/oauth2/v1/certs

If this is too risky in a particular client library, then the change should be:
- https://accounts.google.com/o/oauth2/token -> https://www.googleapis.com/oauth2/v3/token
- *DO NOT* Change https://www.googleapis.com/oauth2/v1/certs

**Comment by broady** [comment]
Yes, this is the right repo.

**Comment by JustinBeckwith** [comment]
👋 We'd like to get this fixed up for our partner team.  Can anyone take a look?  Anything we can do to help?

**Comment by jadekler** [comment]
https://go-review.googlesource.com/c/oauth2/+/136356

Note: I see no mention of audience other than a field that the user can pass in to `JWTAccessTokenSourceFromJSON`.

**Comment by paulquerna-okta** [comment]
I believe the blacklists in providerAuthHeaderWorks may need to add `oauth2.googleapis.com` like it has `accounts.google.com`?

https://github.com/golang/oauth2/blob/master/internal/token.go#L94

The Google OIDC Discovery Document changed over to the new URL tonight[1], and broke our code, because the new URL referenced in the discovery document does not get marked as busted auth.

[1] - https://accounts.google.com/.well-known/openid-configuration

**Comment by paulquerna-okta** [comment]
See PR https://github.com/golang/oauth2/pull/327

**Comment by oztaskin** [comment]
What is the recommended Client type for Apple TV applications? I need Google Drive read-only, and Google Calendar read-only scopes.
