### ISSUE TITLE
tag repository with a semver tag

### ISSUE THREAD

**Issue by dmitris** [golang/oauth2#330]
Could you please tag the repo with a semver tag like `v1.0.0` or `v.0.5.0`?  This will make requiring and replacing the oauth2 module in `go.mod` files easier.  Thanks.

**Comment by bradfitz** [comment]
@bcmills, I'm fine with this. Any objections?

**Comment by bcmills** [comment]
This morning @rsc suggested that we should probably have a uniform tagging policy for all of the `x/` repos, and it should probably follow the Go minor releases.

In the meantime, it should be easy enough to `go get golang.org/x/oauth2` at any given revision, and you can always `replace` it without a version at all. Why is important to have specific tags?

**Comment by hronik1** [comment]
Would also greatly appreciate this, as it would allow using semantic versioning of the dependency in dep.

**Comment by bradfitz** [comment]
@hronik1, that doesn't answer @bcmills's question, though.

You can use semantic versions today without a go.mod file. They're just ugly semantic versions (https://semver.org/#spec-item-10).

If you just want to agree, see https://github.com/golang/go/wiki/NoPlusOne

**Comment by hronik1** [comment]
@bradfitz, sorry, I didn't feel like I was +1'ing as I was adding context that I was using `dep`, which uses git tags to handle its semantic versioning. My apologies for not being more explicit about that.

**Comment by creachadair** [comment]
Now that there is a `go.mod` file (since fd3eaa14), would you be willing to revisit this request?

**Comment by bradfitz** [comment]
Still no objections. We're waiting on the green light from @bcmills.

**Comment by creachadair** [comment]
Ping @bcmills, can you please take another look when you have a moment?

**Comment by bcmills** [comment]
It probably doesn't make much difference for `oauth2` in particular, but for most of the `x` repos the versioning strategy significantly depends on the resolution to #30241. It may be that we will want to version the `x` repos in lock-step with the toolchain and standard library.

**Comment by creachadair** [comment]
That would certainly make sense—I'd very much like to have a way to tell which versions of the `x` packages are compatible with various Go releases. So is this issue blocked on resolution of 30241?

**Comment by creachadair** [comment]
(Interestingly, https://github.com/golang/text _does_ already have release tags, but as far as I can tell is the only `x` repository for which that is the case)

**Comment by bcmills** [comment]
> So is this issue blocked on resolution of 30241?

Given that tagging a release of `oauth2` isn't particularly urgent (you can use a pseudo-version in the meantime), I think so, yes.

**Comment by saurcery** [comment]
I did hit this particular semver tag issue with Go 1.13.1
```
go mod tidy

verifying golang.org/x/oauth2@v0.0.0-20190630083822-0f29369cfe45/go.mod: golang.org/x/oauth2@v0.0.0-20190630083822-0f29369cfe45/go.mod: reading https://sum.golang.org/lookup/golang.org/x/oauth2@v0.0.0-20190630083822-0f29369cfe45: 410 Gone

```

likely when using `google.golang.org/grpc@v1.19.0 cloud.google.com/go@v0.26.0`

**Comment by campoy** [comment]
Any updates on having semantic versioning for this library?
