### ISSUE TITLE
Peplink OAuth 

### ISSUE THREAD

**Issue by undeadindustries** [golang/oauth2#352]
Please add the below token URL to brokenAuthHeaderProviders in token.go
https://api.ic.peplink.com/api/oauth2/token

**Comment by bradfitz** [comment]
For now, use:
https://godoc.org/golang.org/x/oauth2#RegisterBrokenAuthHeaderProvider

But also, I'm working on killing it and making this all automatic in #111 and CL:
https://go-review.googlesource.com/c/oauth2/+/157820

So I'll close this for now.
