### ISSUE TITLE
Oauth2 use of internal package not allowed

### ISSUE THREAD

**Issue by arturasjurev** [golang/oauth2#355]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.11.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/arturas/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/arturas/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/arturas/development/advertiza/go/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build150102045=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?
Building my project which includes `"github.com/golang/oauth2"` package outside of go path (with go modules)

### What did you expect to see?
Successful compilation

### What did you see instead?
<pre>../../../go/pkg/mod/github.com/golang/oauth2@v0.0.0-20181203162652-d668ce993890/oauth2.go:20:2: use of internal package golang.org/x/oauth2/internal not allowed</pre>

I almost understand what is the issue here, but my concern is how can I workaround this? Couldn't find clear guidelines on how to properly fix this/workaround from my side.
After surfing issues, could not find similar one. Sorry in advance if this is dup.

**Comment by bradfitz** [comment]
@bcmills, is there a golang/go bug about this already?

If not, we can transfer this one to the golang/go repo (new GitHub feature).

**Comment by bcmills** [comment]
The canonical module path for the repo at `github.com/golang/oauth2` is `golang.org/x/oauth2`, not `github.com/golang/oauth2`, and its imports of its own internal packages are only allowed from within that canonical path.

As far as I can tell, the error message here is correct. (The fix is to use the correct import path for `oauth2`, and perhaps to add a `go.mod` file with a module declaration to `oauth2` so that the incorrect path will be diagnosed more clearly.)

<details>

```
$ go mod init golang.org/issue/scratch
go: creating new go.mod: module golang.org/issue/scratch

$ cat > main.go
package main
import _ "github.com/golang/oauth2"
func main() {}

$ go build
go: finding github.com/golang/oauth2 latest
go: downloading github.com/golang/oauth2 v0.0.0-20181203162652-d668ce993890
go: extracting github.com/golang/oauth2 v0.0.0-20181203162652-d668ce993890
go: finding golang.org/x/oauth2/internal latest
go: finding golang.org/x/oauth2 latest
go: downloading golang.org/x/oauth2 v0.0.0-20181203162652-d668ce993890
go: extracting golang.org/x/oauth2 v0.0.0-20181203162652-d668ce993890
go: finding golang.org/x/net/context/ctxhttp latest
go: finding golang.org/x/net/context latest
go: finding golang.org/x/net latest
go: downloading golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: extracting golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
_gopath/pkg/mod/github.com/golang/oauth2@v0.0.0-20181203162652-d668ce993890/oauth2.go:20:2: use of internal package golang.org/x/oauth2/internal not allowed

$ sed -i 's,github.com/golang,golang.org/x,' main.go

$ go build

$
```

</details>

**Comment by bcmills** [comment]
>  perhaps to add a `go.mod` file with a module declaration

Sent https://golang.org/cl/157137.
