### ISSUE TITLE
add a URL to providerAuthHeaderWorks

### ISSUE THREAD

**Issue by undeadindustries** [golang/oauth2#365]
Please add metrowan.metrowireless.com to providerAuthHeaderWorks

**Comment by bradfitz** [comment]
For now, use:
https://godoc.org/golang.org/x/oauth2#RegisterBrokenAuthHeaderProvider

But also, I'm working on killing it and making this all automatic:
https://go-review.googlesource.com/c/oauth2/+/157820

So I'll close this for now.
