### ISSUE TITLE
panic error raised 'nil pointer dereference' for facebook provider

### ISSUE THREAD

**Issue by sachinsu** [golang/oauth2#381]
Below code that exchanges code for accesstoken is raising 'runtime error: invalid memory address or nil pointer dereference' error on call to Exchange method, 

`oauthConf := &oauth2.Config{
		ClientID:  os.Getenv("CLIENTID"),
		ClientSecret: os.Getenv("SECRET"),
		RedirectURL: os.Getenv("CALLBACKURL"),
		Scopes: []string{"email"},
		Endpoint: facebook.Endpoint,
	}	

	// fmt.Printf("\nconfvar:%s\n", oauthConf)
	// fmt.Printf("\nconfno:%s\n", oauth2.NoContext)
	// fmt.Printf("\ncode:%s\n", input.Code)
	
	token, err := oauthConf.Exchange(oauth2.NoContext, input.Code)`

Stack trace is
`                                                                                                            
runtime error: invalid memory address or nil pointer dereference                                            
../panic.go:82 (0x441025)                                                      
        panicmem: panic(memoryError)                                                                        
../signal_windows.go:233 (0x440ec0)                                            
        sigpanic: panicmem()                                                                                
../fbauth.go:45 (0xa1524c)                                 
        (*OAuthContext).FacebookAuth: token, err := oauthConf.Exchange(oauth2.NoContext, input.Code)        `

Any ideas?

**Comment by bradfitz** [comment]
There's not enough information here to help you.

What is fbauth.go? Where is its code? What is the complete stack trace, formatted correctly without all being smushed onto one line?

**Comment by sachinsu** [comment]
fbauth.go is file containing below code, 

```
   oauthConf := &oauth2.Config{
                 ClientID: os.Getenv("BILLME_FACEBOOK_CLIENTID"),
                 ClientSecret: os.Getenv("BILLME_FACEBOOK_SECRET"),    
		RedirectURL: os.Getenv("BILLME_FACEBOOK_CALLBACKURL"),
		Scopes: []string{"public_profile","email"},
		Endpoint: facebook.Endpoint,
	}	

    token, err := oauthConf.Exchange(oauth2.NoContext, input.Code)
```
and stack trace is, 
```
runtime error: invalid memory address or nil pointer dereference ../panic.go:82 
(0x441025) panicmem: panic(memoryError) ../signal_windows.go:233 
(0x440ec0) sigpanic: panicmem() ../fbauth.go:45 
(0xa1524c) (*OAuthContext).FacebookAuth: token, err := oauthConf.Exchange(oauth2.NoContext, input.Code) 
```

Line 45 is where Exchange method is called.

**Comment by bradfitz** [comment]
Well, looks like your oauthConf is nil (wrong scope) or your `input` is nil trying to find `input.Code`.

Anyway, without details I can't help you debug your code, so I'm closing this.

**Comment by DarthSett** [comment]
Facing the same issue when trying to exchange authentication code for access-token from google calendar api
