### ISSUE TITLE
TokenSource:  receive `scope ...string` param so that I can fetch scoped tokens

### ISSUE THREAD

**Issue by mihaiav** [golang/oauth2#405]
I find myself in need to use scoped AccessToken(s). Currently in order to do that I need to create/copy a *Config each time I need a scoped token. 
   I believe changing the TokenSource interface signature from ``Token() (*Token, error)`` to ``Token(scope ...string) (*Token, error)`` is relatively backward compatible and would make the library more useful for clients that need scoped tokens. If such a change is accepted I could send a CL for review.

**Comment by bradfitz** [comment]
That is not a backwards compatible change. See https://play.golang.org/p/9hd7gJCK6FP

Before attempting a solution, let's back up and discuss the problem. I don't quite follow what you mean by a "scoped AccessToken".

**Comment by mihaiav** [comment]
After further consideration I believe it's best to close this issue. It's not really backward compatible and  I was "abusing" the `scope` param for a more unusual workflow. I'm not sure if it's worth to discuss it further but overall here how it works :
  - device(i.e. setup-box) gets authenticated with a "master" auth provider using the device auth workflow.
  - The device then requests "scoped/different" accessTokens from the auth provider on behalf of various `origin`. The accessToken returned is a JWT with the `origin` as `aud` param.  

Request: `` 
GET /token?scope=example.com&grant_type=refresh_token&refresh_token=tGzv3J
``

Response:
The accessToken returned would be a JWT that includes "example.com" as `aud` field, thus  it becomes usable to access restricted content from the origin ("example.com")
