### ISSUE TITLE
add support for response_mode=form_post

### ISSUE THREAD

**Issue by balonik** [golang/oauth2#408]
Hi,
please add support for `response_mode=form_post` as described in https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html

Thanks.

**Comment by jnoga** [comment]
Maybe I'm a bit late...

You can set `response_mode` to `form_post` when calling [AuthCodeURL](https://github.com/golang/oauth2/blob/master/oauth2.go#L150) with an `AuthcodeOption` option set by [SetAuthURLParam](https://github.com/golang/oauth2/blob/master/oauth2.go#L134)

Example:

`oauth2.AuthCodeURL(state,` oauth2.SetAuthURLParam("response_mode", "form_post"))`

Hope it's still helpfull after 8 months :sweat_smile:
