### ISSUE TITLE
Check PayPal and VKontakte

### ISSUE THREAD

**Issue by nikolay-turpitko** [golang/oauth2#41]
Hi guys,

I've just stumbled upon your lib and it seems active and most code reused from goauth2.
So, may I ask you to review my small changes for goauth2, that I make to use it with LinkedIn, PayPal and VKontakte and to decide if they are relevant for your lib?

Here is the diff: https://code.google.com/r/nikolay-goauth2/source/diff?spec=svn90e22c7acbc4a815996ec16c939f11f83a4abf6c&r=90e22c7acbc4a815996ec16c939f11f83a4abf6c&format=side&path=/oauth/oauth.go

Your Transport.RoundTrip() method seems to take care of issue with "Authorization" header for LinkedIn a way better then mine, but other issues may still affect your code. As I remember causes of those changes: PayPal's "expires_in" field was a string (not a number) and won't decode from json well and VKontakte returns extra uesful "user_id" field (in response to retrieve token request).

I made changes some 10 month ago and cannot provide better explanations (also things may change already), but changed code is in production and seems to work.

Sorry, cannot test your lib myself yet.

**Comment by bradfitz** [comment]
Could you send patches against this repo instead? Ideally with tests, too.

We're going to deprecate the goauth2 code.

**Comment by nikolay-turpitko** [comment]
I finally find some time to create several accounts, and make some tests.
Here are my suggested changes and sample tests: https://go-review.googlesource.com/#/c/6920/.

**Comment by nikolay-turpitko** [comment]
I've split it up to:
https://go-review.googlesource.com/6924
https://go-review.googlesource.com/6925
https://go-review.googlesource.com/6926

**Comment by rakyll** [comment]
2167774 closes this issue, thanks to @nikolay-turpitko.
