### ISSUE TITLE
Raw JSON support for GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by alexcurtin** [golang/oauth2#415]
Is there a particular reason this library doesn't support generating credentials from a service account JSON that is stored as an environment variable, e.g. 
```
$ export GOOGLE_APPLICATION_CREDENTIALS=`{
  "type": "service_account",
  "project_id": "",
  "private_key_id": "",
  "private_key": "",
  "client_email": "",
  "client_id": "",
  "auth_uri": "",
  "token_uri": "",
  "auth_provider_x509_cert_url": "",
  "client_x509_cert_url": ""
}`
```

Instead of requiring a path to a file? This would help containerized workloads in GKE where we inject run time secrets as environment variables but don't want to write secrets to a path on disk.

The code in question: https://github.com/golang/oauth2/blob/master/google/default.go#L61

**Comment by seankhliao** [comment]
This is how `GOOGLE_APPLICATION_CREDENTIALS` is specced to work https://cloud.google.com/docs/authentication/application-default-credentials .
