### ISSUE TITLE
Cannot import the package

### ISSUE THREAD

**Issue by rakyll** [golang/oauth2#446]
```
import (
	_ "golang.org/x/oauth2"
)

func main() {}
```

Building the package fails with the following message and is breaking many projects that has a dependency to oauth2:

```
go: finding module for package golang.org/x/oauth2
go: found golang.org/x/oauth2 in golang.org/x/oauth2 v0.0.0-20200902213428-5d25da1a8d43
go: golang.org/x/oauth2@v0.0.0-20200902213428-5d25da1a8d43 requires
	cloud.google.com/go@v0.65.0 requires
	cloud.google.com/go/storage@v1.10.0 requires
	cloud.google.com/go@v0.57.0 requires
	cloud.google.com/go/bigquery@v1.4.0 requires
	cloud.google.com/go@v0.52.0 requires
	golang.org/x/exp@v0.0.0-20191227195350-da58074b4299/go.mod: verifying module: golang.org/x/exp@v0.0.0-20191227195350-da58074b4299/go.mod: cannot authenticate record data in server response
```

cc @rsc

**Comment by rsc** [comment]
I can't reproduce this.

It means that somehow the record for that go.mod is not matching the checksum in the database.
It could be corrupted or it could simply be truncated.
The record is loaded from the web but is also cached on disk.
A record loaded from the web is not written to the disk cache until after it has been authenticated, though.
So if the command is using the on-disk copy, it means the corruption happened after the correct one was written.
Or it may be that you didn't have this record cached and were trying to load from the web, and somehow the web result was being truncated or corrupted in transit. Most corruptions or truncations would result in the record not parsing, though, which would produce a different error message.

Anyway, lots of thoughts, no obvious answers. 
Can you share a bit more about go version, how many machines you see this on, whether it is still happening?

**Comment by rakyll** [comment]
It's very likely that this is only affecting my setup. Thanks for the comments above, I will be able to narrow down the possibilities much faster.  I'll diagnose it further when I have time and file an issue if it turns out to be something else. 

If anyone is seeing the same issue, please let us know. I'm closing this issue believing it's an issue with my setup.

**Comment by rsc** [comment]
For what it's worth, this is the fetch that would have been failing if it was a web issue:

```
% curl 'https://sum.golang.org/lookup/golang.org/x/exp@v0.0.0-20191227195350-da58074b4299'
565615
golang.org/x/exp v0.0.0-20191227195350-da58074b4299 h1:zQpM52jfKHG6II1ISZY1ZcpygvuSFZpLwfluuF89XOg=
golang.org/x/exp v0.0.0-20191227195350-da58074b4299/go.mod h1:2RIsYlXP63K8oxa1u096TMicItID8zy7Y6sNkU49FU4=

go.sum database tree
1746116
+EOpGhQBrMVEcZqC8Dd0+zh6FGUQhufW8pwJZDl//XM=

— sum.golang.org Az3grn6arXlgu9br11PaPzSvFmUgfwILARu8Ea5HI+2kYYb9NigDa6fO/otFxXyj9DMcdE05kd2mgIkGEUqlkTR/CQc=
% 
```

Most truncations or corruptions would get a syntax error parsing the record. 

The only way to get the message you were seeing from a truncation would be if it were truncated after the first line but before the first blank line. That is, to get through to the error being reported, the response to this fetch would need to start with a decimal integer on a line by itself (and not too big or else it would index out of the checksum tree) and not contain any blank lines. The blank line introduces a signed tree root, which the go command would attempt to parse and merge into the local state. There's zero chance of that succeeding without being real and complete. 

An in-flight corruption in the first three lines would also produce the error you were seeing, provided that it (1) kept the first line containing only a small decimal integer, (2) did not introduce a new blank line, and (3) left the blank line and everything after it alone.
