### ISSUE TITLE
Question : What is the difference between `endpoints/endpoints.go` and each service's endpoint?

### ISSUE THREAD

**Issue by sabhiram** [golang/oauth2#452]
Why are these duplicated? Is one auto-generated form the other?

**Comment by bradfitz** [comment]
See https://github.com/golang/oauth2#policy-for-new-packages

**Comment by bradfitz** [comment]
@broady, I lost access to close bugs, so all yours. :)

**Comment by b01** [comment]
I'm confused as to HOW to update the endpoints. What is the process for contributing an update just for an endpoint?
