### ISSUE TITLE
Deprecate code.google.com/p/goauth2

### ISSUE THREAD

**Issue by rakyll** [golang/oauth2#5]

**Comment by rakyll** [comment]
I think this issue is now blocked by https://github.com/golang/oauth2/issues/70. We need to land go1.4 to Managed VMs before we announce stability.

**Comment by bradfitz** [comment]
I've sent https://code-review.googlesource.com/#/c/1670 to address #70

**Comment by bradfitz** [comment]
Okay, can we do this now? :)

**Comment by rakyll** [comment]
Yes.
