### ISSUE TITLE
Impossible to use with Twitter v2 API

### ISSUE THREAD

**Issue by mholt** [golang/oauth2#534]
Twitter v2's API requires setting Basic auth in the Authorization header while also encoding the client_id into the body:

https://developer.twitter.com/en/docs/authentication/oauth-2-0/user-access-token (see step 3)

```
curl --location --request POST 'https://api.twitter.com/2/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header Authorization: Basic V1ROclFTMTRiVWhwTWw4M2FVNWFkVGQyTldNNk1UcGphUTotUm9LeDN4NThKQThTbTlKSXQyZm1BanEzcTVHWC1icVozdmpKeFNlR3NkbUd0WEViUA==\
--data-urlencode 'code=VGNibzFWSWREZm01bjN1N3dicWlNUG1oa2xRRVNNdmVHelJGY2hPWGxNd2dxOjE2MjIxNjA4MjU4MjU6MToxOmFjOjE' \
--data-urlencode 'grant_type=authorization_code' \
--data-urlencode 'client_id=rG9n6402A3dbUJKzXTNX4oWHJ' \
--data-urlencode 'redirect_uri=https://www.example.com' \
--data-urlencode 'code_verifier=challenge'
```

The current API for this library where you can only set either headers or params, is incompatible with Twitter. Setting `AuthStyleInHeader` omits `client_id` in the body and we get `Missing required parameter [client_id].` error, whereas setting `AuthStyleInParams` gives an error, `Missing valid authorization header`.

Please provide an option to use both.

**Comment by mholt** [comment]
This is the offending code:

https://github.com/golang/oauth2/blob/d3ed0bb246c8d3c75b63937d9a5eecff9c74d7fe/internal/token.go#L151-L178

It should not be a boolean condition as to whether the client_id goes in the body or a header; we should be able to set both instead of either/or.

**Comment by mholt** [comment]
As a workaround, manually adding the `client_id` to the URL (which is not where it belongs) does make it work:

```go
err = cfg.Exchange(ctx, code, 
    oauth2.SetAuthURLParam("code_verifier", pkceChallenge),
    oauth2.SetAuthURLParam("client_id", clientID))
```

(Don't mind my code_verifier parameter, that's for the PKCE extension, which Twitter also requires.)

This only works because [url values are cloned into the body](https://github.com/golang/oauth2/issues/534#L161). It is not correct to put client_id in the URL, however, this does work as a hack until this is fixed.

**Comment by mholt** [comment]
Unfortunately, the above workaround only works for the initial token.

A TokenSource is impossible to fix because the `Token()` method does not let you manually add parameters like the `Exchange()` method does.

We cannot add parameters here to `tokenRefresher`: https://cs.opensource.google/go/x/oauth2/+/d3ed0bb2:oauth2.go;l=270-273

So it appears that this library is impossible to use with Twitter's API. I've brought this up with Twitter and it's on their "roadmap" but one of you will have to budge in order for this to work. https://twittercommunity.com/t/trying-to-get-oauth-2-0-token-receiving-missing-valid-authorization-header-error/163633/6?u=mholt6

**Comment by cazicbor** [comment]
Anything new about this? I've been working on oauth2 with Twitter's API for a week now and I've just discovered this issue...

**Comment by mholt** [comment]
Twitter seems to have fixed their v2 API. I no longer need to add `oauth2.SetAuthURLParam("client_id", clientID)`.

**Comment by RazaGR** [comment]
@mholt I am facing similar issue, mind sharing your solution code? Thanks

`Response: {"error":"invalid_request","error_description":"Missing required parameter [code_verifier]."}`
