### ISSUE TITLE
Can Token support custom token structure？

### ISSUE THREAD

**Issue by yongxingMa** [golang/oauth2#551]
Now my return value is wrapped with a layer of。
Not like this, 
```
{
"accessToken":"XXX"
"tokenType":"XXX"
"refreshtoken":"XXX"
}
```
but like this:
```
{
"code":200,
"messsage":"success",
"data":
    {
    "accessToken":"XXX"
    "tokenType":"XXX"
    "refreshtoken":"XXX"
    }
}
```

**Comment by jamietanna** [comment]
I don't think this would make sense, as that's not an OAuth2 compliant solution. This wouldn't work with any OAuth2 clients without code changes - is there any reason the response body is returned like so?

**Comment by jamietanna** [comment]
May be related to #526?

**Comment by yongxingMa** [comment]
Thank you @jamietanna
