### ISSUE TITLE
golang.org/x/net dependency is superfluous

### ISSUE THREAD

**Issue by misha-ridge** [golang/oauth2#565]
There is a single use of golang.org/x/net dependency in the whole library: `ctxhttp.Do`.

It can be easily inlined and the dependency dropped: https://github.com/ridge/oauth2/commit/b7f928651e695e33d6ec3cdf2213df1b5475bbbe

**Comment by hickford** [comment]
Direct dependency removed https://github.com/golang/oauth2/commit/e07593a4c41a489556d019d1ad4d82e9ee66b4a7
