### ISSUE TITLE
Crypto Go ：we are a research group to help developers build secure applications.

### ISSUE THREAD

**Issue by 1047261438** [golang/oauth2#585]
Hi, we are a research group to help developers build secure applications. We designed a cryptographic misuse detector (i.e., CryptoGo) on Go language. We found your great public repository from Github, and several security issues detected by CryptoGo are shown in the following. 
Note that the cryptographic algorithms are categorized with two aspects: security strength and security vulnerability based on NIST Special Publication 800-57 and other public publications. Moreover, CryptoGo defined certain rules derived from the APIs of Go cryptographic library and other popular cryptographic misuse detectors. The specific security issues we found are as follows:
(1)	Location: jws/jws.go:160; 
        Broken rule: R-07: RSASSA-PKCS1-v1_5 is deprecated;
(2)	Location: google/internal/externalaccount/aws.go:274; 
        Broken rule: R-08: HTTP is insecure;
 We wish the above security issues could truly help you to build a secure application. If you have any concern or suggestion, please feel free to contact us, we are looking forward to your reply. Thanks.

**Comment by jeromedoucet** [comment]
Hello @1047261438 !

1

I am not very well experienced in cryptography, but when I check the related RFC(s), we may found the [list](https://www.rfc-editor.org/rfc/rfc7518#section-3.1) of accepted signing algorism for JSW with some recommendations.

We can see that "RSASSA-PKCS1-v1_5 using SHA-256" (the one :) ) is not only possible, but recommended. From this RFC perspective, it seems that this algorism is far from being deprecated.

Moreover, I found nothing related to "RSASSA-PKCS1-v1_5" deprecation, only some resources on "RSAES-PKCS1-v1.5" deprecation (really, really old deprecation, about 20 years). But it's an encryption, not a signing algorism.

Can you provide more informations on that deprecation ?

2

I am not sure to fully understand your point.

This rely uppon some attributes of `awsCredentialSource` type : 
- IMDSv2SessionTokenURL
- RegionURL
- CredVerificationURL

But theses are AWS production URL. Not a chance to be insecure (HTTP without TLS, I mean). The only context we may have HTTP URL in that field is for some unit/integrations tests (but even in that case, a `httptest.NewTLSServer` may be used :) ).

What is the problem exactly ?

Thank you !

**Comment by 1047261438** [comment]
Hello,


&nbsp; &nbsp;Thank you for your feedback.
&nbsp; &nbsp; we are just a research group to help developers build secure applications. We designed a cryptographic misuse detector (i.e., CryptoGo) on Go language.

&nbsp; &nbsp; We found your great public repository from Github, and hope that the design basis of CryptoGo can help your development work.

&nbsp; &nbsp; The detection principle of CryptoGo are as follows: First, we categorized all the cryptographic algorithms with two aspects: security strength and security vulnerability based on NIST Special Publication 800-57 and other public publications.

&nbsp; &nbsp; The classification results are shown in the following table.



&nbsp; &nbsp; Second, CryptoGo defined 12 rules derived from the APIs of Go cryptographic library and other popular cryptographic misuse detectors.

&nbsp; &nbsp; The rules are shown in the following table.



&nbsp; &nbsp;R-07 forbids insecure padding oracles in RSA. Two padding algorithms are provided in the official Go cryptographic library for RSA: PKCS\#1-v1.5 and optimal asymmetric encryption padding (OAEP). As PKCS\#1-v1.5 padding format may be used to recover the RSA private key in different settings [1], thus new secure padding method (i.e., OAEP) is proposed and recommended.


&nbsp; &nbsp;We wish the above security suggests could truly help you to build secure applications.
&nbsp; &nbsp;If you have any concern or suggestion, please feel free to contact us, we are looking forward to your reply.







[1] Sazzadur Rahaman, Haipeng Cai, Omar Haider Chowdhury, and Danfeng Daphne Yao. 2021. From Theory to Code: Identifying Logical Flaws in Cryptographic Implementations in C/C++. IEEE Transactions on Dependable and Secure Computing (2021)

[2] Jakob Jonsson and Burt Kaliski. 2003. Public-Key Cryptography Standards (PKCS) #1: RSA Cryptography Specifications Version 2.1. RFC 3447. (Feb. 2003).&nbsp;https://doi.org/10.17487/RFC3447





Thanks again.

&nbsp;

Sincerely,

CryptoGo Team.&nbsp;










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "golang/oauth2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月29日(星期一) 凌晨3:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [golang/oauth2] Crypto Go ：we are a research group to help developers build secure applications. (Issue #585)





 
Hello @1047261438 !
 
1
 
I am not very well experienced in cryptography, but when I check the related RFC(s), we may found the list of accepted signing algorism for JSW with some recommendations.
 
We can see that "RSASSA-PKCS1-v1_5 using SHA-256" (the one :) ) is not only possible, but recommended. From this RFC perspective, it seems that this algorism is far from being deprecated.
 
Moreover, I found nothing related to "RSASSA-PKCS1-v1_5" deprecation, only some resources on "RSAES-PKCS1-v1.5" deprecation (really, really old deprecation, about 20 years). But it's an encryption, not a signing algorism.
 
Can you provide more informations on that deprecation ?
 
2
 
I am not sure to fully understand your point.
 
This rely uppon some attributes of awsCredentialSource type :
  
IMDSv2SessionTokenURL
 
RegionURL
 
CredVerificationURL
  
But theses are AWS production URL. Not a chance to be insecure (HTTP without TLS, I mean). The only context we may have HTTP URL in that field is for some unit/integrations tests (but even in that case, a httptest.NewTLSServer may be used :) ).
 
What is the problem exactly ?
 
Thank you !
