### ISSUE TITLE
Unable to clone from https://cs.opensource.google/go/x/oauth2

### ISSUE THREAD

**Issue by nhooyr** [golang/oauth2#588]
https://pkg.go.dev/golang.org/x/oauth2 says the repository for oauth2 is https://cs.opensource.google/go/x/oauth2 but I can't seem to clone from there. I get:

```
$ git clone https://cs.opensource.google/go/x/oauth2 .
Cloning into '.'...
fatal: https://cs.opensource.google/go/x/oauth2/info/refs not valid: is this a git repository?
```

I wasn't sure if I had to pass in a less nested path like /go/x or /go but same error cloning those with the cs.opensource.google domain. Any ideas?

I was able to clone from GitHub just fine.

**Comment by insected** [comment]
hi,

sources you can download from https://github.com/golang/oauth2

for development please follow contributor documentation https://go.dev/doc/contribute
repository url is: https://go.googlesource.com/oauth2

greetings
Marcin

**Comment by muir** [comment]
@seankhliao   You closed this, but didn't provide any useful information for anyone else wanting to clone the repo.

**Comment by muir** [comment]
```
git clone https://go.googlesource.com/oauth2
```

**Comment by nhooyr** [comment]
Thanks @muir
