### ISSUE TITLE
Cannot get id_token when using impersonated service account: 

### ISSUE THREAD

**Issue by liufuyang** [golang/oauth2#600]
```golang
func main() {
	ctx := context.Background()
	defaultTokenSource, _ := google.DefaultTokenSource(
		ctx,
		"https://www.googleapis.com/auth/cloud-platform",
	)
	token, err := defaultTokenSource.Token()
	idToken, ok := token.Extra("id_token").(string)
	if !ok {
		fmt.Println("No id_token")
	}
	fmt.Println(err)
	fmt.Println(idToken)
}
```
With a simple piece of code above, if a normal google user authentication is used, one could get 
refresh token and also the `id_token`, seem from the debug screenshot:
![image](https://user-images.githubusercontent.com/161689/197275849-9012db18-5402-40e4-92a4-1df0640e9d2f.png)

But when an impersonated service account is used (by setting the `key.json` via setting `GOOGLE_APPLICATION_CREDENTIALS`, and the json key is got by running `gcloud --impersonate-service-account xxxsa@xxx.iam.gserviceaccount.com auth application-default login`), there is no refresh token got and also no `raw` and no `id_token` (a JWT token) on it
![image](https://user-images.githubusercontent.com/161689/197276497-71d8a9d9-8a81-41c5-8404-d1412c9caaeb.png)

Resulting in the code above prints `no id_token` and no JWT token can be retrieved.

Is this expected behaviour? Thanks.

**Comment by seankhliao** [comment]
I believe the appropriate place is with googleapis/google-api-go-client#873

**Comment by liufuyang** [comment]
@seankhliao May I ask how is this package related to the https://github.com/googleapis/google-api-go-client/pull/1792 change?
