### ISSUE TITLE
Feature request: PKCE

### ISSUE THREAD

**Issue by tonimelisma** [golang/oauth2#603]
Many OAuth providers no longer support many flows without PKCE, yet the `oauth2` library doesn't have any built-in support. Generating code code verifiers and challenges must be done with a third party library, both need to be attached via unspecified Auth URL Parameters, etc.

Would there be interest in merging a PR that provided
- Functions to generate code verifiers and challenges
- Included them in authentication and token exchange flows as part of standard data structures with clear PKCE semantics
- Included working example code in documentation for above

**Comment by tonimelisma** [comment]
You can use https://github.com/nirasan/go-oauth-pkce-code-verifier for the PKCE part but you'll need to mash it up manually with this oauth2 library, which is mainly unmaintained nowadays.

**Comment by hickford** [comment]
https://pkg.go.dev/golang.org/x/oauth2/authhandler#TokenSourceWithPKCE does some of the work, although you still need to generate the challenge and verifier:

```go
func randomString(n int) string {
	data := make([]byte, n)
	if _, err := io.ReadFull(rand.Reader, data); err != nil {
		panic(err)
	}
	return base64.StdEncoding.EncodeToString(data)
}

func generatePKCEParams() *authhandler.PKCEParams {
	verifier := randomString(32)
	sha := sha256.Sum256([]byte(verifier))
	challenge := base64.URLEncoding.WithPadding(base64.NoPadding).EncodeToString(sha[:])
	return &authhandler.PKCEParams{
		Challenge:       challenge,
		ChallengeMethod: "S256",
		Verifier:        verifier,
	}
}
```

**Comment by hickford** [comment]
Proof Key for Code Exchange by OAuth Public Clients ([RFC 7636](https://datatracker.ietf.org/doc/rfc7636/)) is important to use OAuth securely, especially on public clients. OAuth 2.1 makes code_challenge and code required by default (dropping the PKCE name) https://datatracker.ietf.org/doc/id/draft-ietf-oauth-v2-1-00.html#section-9.8

> The properties code_challenge and code_verifier are adopted from the OAuth 2.0 extension known as "Proof-Key for Code Exchange", or PKCE ([RFC7636]) where this technique was originally developed.
>
> Clients MUST use code_challenge and code_verifier and authorization servers MUST enforce their use except under the conditions described in Section 7.6. In this case, using and enforcing code_challenge and code_verifier as described in the following is still RECOMMENDED.

However oauth2 module doesn't give you any help to use PKCE making it easy to get wrong.

**Comment by hickford** [comment]
Perhaps because the API is awkward, few users appear to be using PKCE:

Only 334 files found on GitHub search https://github.com/search?q=lang%3Ago+SetAuthURLParam+code_challenge&type=code

**Comment by atamgp** [comment]
There is a nice example here, credits to the writer:
https://chrisguitarguy.com/2022/12/07/oauth-pkce-with-go/

**Comment by hickford** [comment]
Comments welcome on proposal https://github.com/golang/go/issues/59835

**Comment by evanfpearson** [comment]
For anyone having issues with the workaround here - you should use `base64.UrlEncoding` for generating the code verifier.
```go
func randomString(n int) string {
	data := make([]byte, n)
	if _, err := io.ReadFull(rand.Reader, data); err != nil {
		panic(err)
	}
	return base64.URLEncoding.WithPadding(base64.NoPadding).EncodeToString(data)
} 
```

**Comment by Integralist** [comment]
I've modified this https://gist.github.com/ogazitt/f749dad9cca8d0ac6607f93a42adf322 example (which worked fine for the most part) and next I'm going to add refresh token behaviour (which was missing from the OP's gist) using information I found here https://auth0.com/docs/get-started/authentication-and-authorization-flow/call-your-api-using-the-authorization-code-flow-with-pkce?_gl=1*e0fclq*_gcl_au*MTMyMzM3ODM3NC4xNjg4MDU3ODU1#refresh-tokens
