### ISSUE TITLE
Add possibility to set deadline on GAE urlfetch.Transports

### ISSUE THREAD

**Issue by hknauer** [golang/oauth2#65]
I originally switched from https://code.google.com/p/goauth2 to this library because it provided the possibility to set the Deadline property of urlfetch.Transport, which is essential when dealing with larger files on GCS.
Unfortunately this is no longer possible in the current implementation with just the one function 

    func AppEngineContext(ctx appengine.Context) oauth2.Option

I propose a new function to supplement or even replace AppEngineContext():

    func AppEngineTransport(trans *urlfetch.Transport) oauth2.Option {
    	return func(opts *oauth2.Options) error {
    		opts.TokenFetcherFunc = makeAppEngineTokenFetcher(trans.Context, opts)
    		opts.Client = &http.Client{
    			Transport: trans,
    		}
    		return nil
    	}
    }

**Comment by rakyll** [comment]
This issue has been address during the redesign, you can build your own RoundTripper.
```
tr := Transport: &oauth2.Transport{
        Source: google.AppEngineTokenSource(ctx),
        Base: &urlfetch.Transport{
            Context: ctx,
        },
}
```
