### ISSUE TITLE
Deps: Upgrade from unsupported google.golang.org/appengine@v1.6.7 => v2

### ISSUE THREAD

**Issue by trakhimenok** [golang/oauth2#656]
Should be upgraded to latest v2, at least https://pkg.go.dev/google.golang.org/appengine/v2@v2.0.4

[Version: v1.6.7](https://pkg.go.dev/google.golang.org/appengine?tab=versions) Latest published: **Oct 13, 2020**
[Version: v2.0.4](https://pkg.go.dev/google.golang.org/appengine/v2?tab=versions) Latest Published: **Jul 11, 2023**

### Related issues:
- https://github.com/googleapis/google-cloud-go/issues/7760
- https://github.com/googleapis/google-api-go-client/issues/2067

#### Environment details

All environments.

#### Steps to reproduce

  1. See go.mod file - https://github.com/golang/oauth2/blob/ac6658e9cb5802cebf9b8fd5f5d58f22bedb527f/go.mod#L8
  2. The google.golang.org/appengine@v1.6.7 is unsupported library should NOT be referenced

**Comment by hickford** [comment]
Is there any doc explaining the difference between appengine library v1 and v2?

Also, is the v1 library definitely unsupported? https://pkg.go.dev/google.golang.org/appengine@v1.6.8 was published August 2023

**Comment by trakhimenok** [comment]
> Is there any doc explaining the difference between appengine library v1 and v2?
> 
> Also, is the v1 library definitely unsupported? https://pkg.go.dev/google.golang.org/appengine@v1.6.8 was published August 2023

The better question if it needs the dependency at all? A good issue advocating for removal - https://github.com/golang/oauth2/issues/615

If this heavy dependency is needed would be good to document why (justification).

**Comment by sg0hsmt** [comment]
This issue should now be resolved.
Dependency was removed at v0.19.0 and there is no longer a dependency on google.golang.org/appengine.

refs: https://github.com/golang/oauth2/commit/3a6776ada799d857cee190d6f517c4afee7c3170
