### ISSUE TITLE
Device Flow: verification_uri vs verification_url for Google.

### ISSUE THREAD

**Issue by nikolay-turpitko** [golang/oauth2#666]
I'm checking newly implemented Device Flow and I've found a minor issue.
[Here](https://github.com/golang/oauth2/blob/master/deviceauth.go#L32):

```
type DeviceAuthResponse struct {
   VerificationURI string `json:"verification_uri"` 
}
```

Verefication URI is decoded from JSON field, named according RFC.

But [here](https://developers.google.com/identity/protocols/oauth2/limited-input-device#success-response), Google uses `verification_url` name. Which is, obviously, contradicts spec, but it would be nice to be able to somehow obtain it anyway.

Would it be possible to add raw data field to `DeviceAuthResponse`, or map with all received fields, or map with additional (not parsed) fields from the response JSON?

**Comment by nikolay-turpitko** [comment]
@hickford Could you please check?

**Comment by hickford** [comment]
> Google uses [`verification_url`](https://developers.google.com/identity/protocols/oauth2/limited-input-device#success-response) which contradicts spec [RFC 8628](https://datatracker.ietf.org/doc/html/rfc8628) `verification_uri`

Have you reported this at developers.google.com?

**Comment by hickford** [comment]
Here's a two-line fix, no change to API https://github.com/golang/oauth2/pull/667

**Comment by nikolay-turpitko** [comment]
> Have you reported this at developers.google.com?

No, I haven't, TBH. From my previous experience it never helps with big corporations.

> Here's a two-line fix that avoids changing the API https://github.com/golang/oauth2/pull/667

This works perfectly!

**Comment by bcmills** [comment]
This appears to be https://issuetracker.google.com/issues/151238144.
