### ISSUE TITLE
Support client credentials grant type

### ISSUE THREAD

**Issue by rakyll** [golang/oauth2#7]
http://tools.ietf.org/html/draft-ietf-oauth-v2-31#section-1.3.4

Allowing TokenFetcher to retrieve a token without a refresh token if grant type is set to `client_credentials`  would solve the issue.

**Comment by agtorre** [comment]
I wrote a patch for this about a week ago, no word back yet, but it seems to work well for me!

https://go-review.googlesource.com/#/c/2983/

**Comment by ezbercih** [comment]
+1
