### ISSUE TITLE
oauth2 is not compatible with Go 1.2?

### ISSUE THREAD

**Issue by cnbuff410** [golang/oauth2#70]
I'm using Managed VM Go runtime and it still only supports 1.2.2 . When I compile the code I got following error:

unknown net.Dialer field 'KeepAlive' in struct literal

I searched online a little bit and seems like it's Go pre1.2 issue. Go 1.3 fixed it, but not supported by Managed VM yet.

Any suggestion on workaround or I have to wait for 1.3 support?

**Comment by bradfitz** [comment]
I've sent https://code-review.googlesource.com/#/c/1670/ to make this package work with Go 1.2.

**Comment by bradfitz** [comment]
And the final one: https://go-review.googlesource.com/2372
