### ISSUE TITLE
optionally skip urlencoding client id and secret in header

### ISSUE THREAD

**Issue by bachmanity1** [golang/oauth2#710]
This is related to https://github.com/golang/oauth2/issues/237.

Although https://tools.ietf.org/html/rfc6749#section-2.3.1 states that clientID & clientSecret must be url encoded in the authorization header some sites don't do this thus resulting in authentication failure.

**Comment by bachmanity1** [comment]
@quartzmo @BigTailWolf can you have look please?

**Comment by quartzmo** [comment]
This is out of scope for me, I help to maintain the Google Cloud functionality in the google subpackage.

**Comment by bachmanity1** [comment]
> This is out of scope for me, I help to maintain the Google Cloud functionality in the google subpackage.

Thanks for your reply! If possible could you please tag someone who could help me? I have authored a PR which has been open for more than 3 weeks now but there hasn't been any reply yet.
