### ISSUE TITLE
support for parsing Google's client_secret.json

### ISSUE THREAD

**Issue by willnorris** [golang/oauth2#73]
After setting up a new credential in https://console.developers.google.com, you're given an option to "Download JSON" credentials, which results in a file of the form:

```json
{
  "installed": {
    "auth_uri":"https://accounts.google.com/o/oauth2/auth",
    "client_secret":"REDACTED",
    "token_uri":"https://accounts.google.com/o/oauth2/token",
    "client_email":"",
    "redirect_uris":["urn:ietf:wg:oauth:2.0:oob","oob"],
    "client_x509_cert_url":"",
    "client_id":"REDACTED",
    "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs"
  }
}
```

As far as I know this isn't a standard format, but I would have expected something in the `google` package to parse this into an `oauth2.Config`, somewhat similar to [`google.JWTConfigFromJSON`](http://godoc.org/golang.org/x/oauth2/google#JWTConfigFromJSON).  So is the expectation simply that you don't use that downloaded JSON file?  Any reason not to support that?

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/#/c/4968/.
