### ISSUE TITLE
allow user to send client_secret for auth_token on any domain.

### ISSUE THREAD

**Issue by code0x9** [golang/oauth2#77]
github enterprise(https://enterprise.github.com/) can run on any domain and need client_secret on auth token request.

**Comment by code0x9** [comment]
I have sent patch : https://go-review.googlesource.com/#/c/2797/
you said "The documentation and commit message are also in the wrong style.". where is your documentation & commit message style guide?

**Comment by adg** [comment]
https://golang.org/doc/contribute.html

Look to the other fields of the struct for the documentation style.

**Comment by code0x9** [comment]
@adg Thank you. I have fully read contribution guide and sent patch set 1 & 2 on go-review(https://go-review.googlesource.com/#/c/2853/)

**Comment by adg** [comment]
Is this a case of GitHub not adhering to the OAuth2 spec? If so, I'd prefer to ask GitHub to fix their implementation rather than pollute the oauth2 package with special cases.

**Comment by code0x9** [comment]
@adg I agree with you and know only github case, but what if these not adhering services provide "enterprise edition" which can be any domain later?
Also, I think we need some other way to bypass this issue until these 3rd party fixes their OAuth2 implements.

**Comment by adg** [comment]
Assuming we won't add a configurable hook, as per the comment:

	// Assume the provider implements the spec properly
	// otherwise. We can add more exceptions as they're
	// discovered. We will _not_ be adding configurable hooks
	// to this package to let users select server bugs.

If they're publicly accessible services, we can add them to the list of exceptions.
If they're only private, you can use a fork of the oauth2 package.

@bradfitz what say you about adding a configurable hook to enable busted auth? Still the same position?

**Comment by bradfitz** [comment]
> Also, I think we need some other way to bypass this issue until these 3rd party fixes
> their OAuth2 implements.

Just fork our code and call it "enterpriseoauth2"
