### ISSUE TITLE
Google Cloud docs use old API

### ISSUE THREAD

**Issue by fixermark** [golang/oauth2#81]
The example of using oauth2 to access Google Cloud Storage from an App Engine application [https://cloud.google.com/appengine/docs/go/googlecloudstorageclient/getstarted] does not align with this library's methods.

**Comment by adg** [comment]
cc @okdave

**Comment by okdave** [comment]
Thanks, I'll take a look.
I've filed an issue on the app engine [issue tracker](https://code.google.com/p/googleappengine/issues/detail?id=11628) too.

**Comment by rakyll** [comment]
This must be resolved now, closing.
