### ISSUE TITLE
Invalid credential on the hour

### ISSUE THREAD

**Issue by karalabe** [golang/oauth2#82]
@adg 

(hunch) There's a small issue with the JWT token expiration mechanism, that kind of started hitting me during a longer run last night: there is a small time window (few secs) between the time a token expires server side and client side (I'm guessing the latency between retrieving and processing the token from the source). Unfortunately, this means, that any request executed during that time frame, will fail with an invalid credential error:

```
googleapi: Error 401: Invalid Credentials, authError
```

A few secs later the token gets refreshed correctly, and all is well for one more hour, when again everything blows up for a few secs :P 

I think the culprit is rather this line of code https://github.com/golang/oauth2/blob/master/jwt/jwt.go#L135, which sets the expiration to exactly the time sent by the server, but doesn't account any possible lags. Would it be possible to cut off a small time allowance from the expiration to allow fetching a new token before the old expires (i.e. 10-30 secs should cover most cases and shouldn't be a burden on the token server)?

Cheers,
  Peter

PS: google's apis, compute engine, micro instance

**Comment by karalabe** [comment]
Hmm, after digging through my logs, I found a failed API request for a very long running storage upload too (4.5 hours upload), where the auth failure occurred after finishing the upload (one gigantic http request I reckon), at closing the stream.

Which is a tad annoying, because now I have to upload 30GB once more :(

**Comment by adg** [comment]
Ugh... can you do partial uploads, spreading the transfer over multiple requests?

**Comment by karalabe** [comment]
I'd rather not complicate if I mustn't :D. I'm running a test locally now with half a minute reduced expiration to see if the errors still pop up or the tokens get refreshed before they get to fail. If it works I'll do the same thing on GCE, and then I'll try and figure out why the upload choked (that doesn't really fit into the error reason).

But this is a loooooooong running task with the 1h expiration... so... time for coffee I guess :D

**Comment by karalabe** [comment]
First report: locally running with a reduced expiration time works as intended, so the fix *seems* to have solved the issue, but let's wait for the GCE instance to reach the hour limit too.

This was the code I inserted to [jwt.go :: Token()](https://github.com/golang/oauth2/blob/master/jwt/jwt.go#L145) before returning:
```go
// Set a small allowance to cater for retrieval latency
if !token.Expiry.IsZero() {
	token.Expiry = token.Expiry.Add(-30 * time.Second)
}
```

**Comment by karalabe** [comment]
Second report: the compute engine instance also refreshes the tokens now in time, and doesn't generate invalid credentials errors any more, so this was definitely one bug to be crushed.

Now the only weird thing I don't get is the upload failure, since that shouldn't have happened during an expired token. Nonetheless I'll wait to see how this fix pans out. I'll get back in 4-5 hours when the upload finishes. Hopefully with some good news :)

**Comment by karalabe** [comment]
Final report: There is a second bug in there. Probably in the client-apis. Even though the token refresher works correctly now, if a storage upload exceeds the refresh threshold, I get an invalid credentials error.

**Comment by rakyll** [comment]
> if a storage upload exceeds the refresh threshold, I get an invalid credentials error.

Not a client, but a Storage API bug. A resumable upload is not supposed to return a 4xx, once you start it. I've asked to the team to fix it (again).

Mailed https://go-review.googlesource.com/#/c/3307/ for the time mismatch issue.

**Comment by karalabe** [comment]
@rakyll Fair enough. Any ideas when - if ever - the storage API is going to get fixed? Currently it's plain impossible to upload a huge file through Go because it either expires the token or DOSes the storage servers with the tiny requests.

**Comment by rakyll** [comment]
We're planning to fix the resumable upload chunk size, so you can work it as a workaround in the meanwhile.

**Comment by karalabe** [comment]
Yes, but since the API currently sucks a bit with the hidden chunk and ReaderAt, and is going to change in 1-2 weeks anyway, I went with a different approach. I've streamed the whole data through gsutils and let *it* figure out how to correctly upload (perverted, but works :P).

Of course it needed some massaging because the trivial approach of streaming the data into the gsutil stdin lead to a weird bandwidth usage of either downloading or uploading, never saturating both links ([see reasoning](https://groups.google.com/forum/#!topic/golang-nuts/434c3YInH_M)), but with a bit of hacking, it works as intended now. And it essentially kept the same API as the storage lib had (dump writer) so I can swap it out when a fix arrives.

All in all, thanks for the efforts you put in :) Now I'm really going to leave this thread alone as it diverged extremely from oauth, just wanted to finish the topic.

```go

// Stream writer based on gsutil to circumvent the token expiration bug.
type gsutilWriter struct {
	command *exec.Cmd
	stdin   io.WriteCloser

	buffer []byte
	data   chan []byte

	quit chan struct{}
	stat error
	eout bytes.Buffer
}

// NewGSUtilWriter creates a stream writer, uploading a single file to GCS.
func newGSUtilWriter(bucket string, path string) (io.WriteCloser, error) {
	// Create a gsutil instance to stream the writer into
	cmd := exec.Command("gsutil", "cp", "-", fmt.Sprintf("gs://%s/%s", bucket, path))

	// Fetch the base writer and start gsutil
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return nil, err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return nil, err
	}

	if err := cmd.Start(); err != nil {
		return nil, err
	}
	// Create the wrapping writer and start the internals
	gsutil := &gsutilWriter{
		command: cmd,
		stdin:   stdin,
		buffer:  make([]byte, 0, 1024*1024),
		data:    make(chan []byte, 64),
		quit:    make(chan struct{}),
	}
	go io.Copy(&gsutil.eout, stderr)
	go gsutil.writer()

	return gsutil, nil
}

// Write inserts a blob into the internal buffers, rotating for output when one
// fills up.
func (w *gsutilWriter) Write(p []byte) (int, error) {
	// If it fits into the buffer, store and return
	if len(w.buffer)+len(p) < cap(w.buffer) {
		w.buffer = append(w.buffer, p...)
		return len(p), nil
	}
	// Otherwise, fill as much as possible and send
	gap := cap(w.buffer) - len(w.buffer)
	w.buffer = append(w.buffer, p[:gap]...)
	select {
	case <-w.quit:
		return gap, errors.New("closed")

	case w.data <- w.buffer:
	}
	// Reset the buffer and try writing again
	w.buffer = make([]byte, 0, cap(w.buffer))
	n, err := w.Write(p[gap:])
	return gap + n, err
}

// Writer forwards the buffered data to the real output stream.
func (w *gsutilWriter) writer() {
	for buf := range w.data {
		if _, w.stat = w.stdin.Write(buf); w.stat != nil {
			break
		}
	}
	close(w.quit)
}

// Close flushes the output buffers and waits for the object insertion to
// complete.
func (w *gsutilWriter) Close() error {
	// Make sure whatever happens, gsutil dies
	defer w.command.Process.Kill()

	// Flush anything in the buffers
	w.data <- w.buffer
	close(w.data)
	<-w.quit

	if w.stat != nil {
		return w.stat
	}
	// Close the gsutil input stream and flush to GCS
	if err := w.stdin.Close(); err != nil {
		return err
	}
	// Wait until the command terminates
	if err := w.command.Wait(); err != nil {
		return fmt.Errorf("%v: %s", err, w.eout.String())
	}
	return nil
}
```
