### ISSUE TITLE
Add "https://www.googleapis.com/" to providerAuthHeaderWorks()

### ISSUE THREAD

**Issue by DiogoDoreto** [golang/oauth2#85]
Trying to login with Google returns this error:

```
oauth2: cannot fetch token: 400 Bad Request
Response: {
 "error": "invalid_request",
 "error_description": "client_secret is missing."
}
```

Adding `https://www.googleapis.com/` to the list of sites that fail to implement OAuth2 spec solves the problem.

**Comment by adg** [comment]
Sent https://go-review.googlesource.com/3873
