### ISSUE TITLE
About the use of token.raw

### ISSUE THREAD

**Issue by HuKeping** [golang/oauth2#87]
Hi there, i am new to Golang and not very familiar with it. There is a problem when I use these oauth2 package to do things:

Some filed which not contained in the Standard Token Struct will returned by my server, For exmaple:
scope: "read write exec"
jti: "123456" 

Due to the 
`json.Unmarshal(body, &token.raw)`
they will be stored in the token.raw, but how can i retrieve these data in token.raw?

Thanks,

**Comment by adg** [comment]
You should use the `Token`'s `Extra` method: http://godoc.org/golang.org/x/oauth2#Token.Extra

**Comment by HuKeping** [comment]
Yeah, that's it! Thanks so much
