### ISSUE TITLE
appengine.go and appenginevm.go should be merged

### ISSUE THREAD

**Issue by themihai** [golang/oauth2#89]
I think there is no need for a separate package now that appengine allows google.golang.org imports [0][1]. 

[0] https://code.google.com/p/googleappengine/issues/detail?id=11670
[1] https://groups.google.com/forum/#!topic/google-appengine-go/RAFdSTwo34w

**Comment by adg** [comment]
Yep, you're right.

**Comment by adg** [comment]
Also, oauth2.Context is no longer necessary.

**Comment by adg** [comment]
Work in progress: https://go-review.googlesource.com/6075 (not ready for review)

**Comment by azr** [comment]
Hey there,

Is this working ? Because we have the exact same problem as [here](http://stackoverflow.com/questions/28188504/setting-up-an-app-engine-context-in-go).

Thanks ! :)
