### ISSUE TITLE
google: Application Default Credentials support

### ISSUE THREAD

**Issue by anthmgoogle** [golang/oauth2#90]
Application Default Credentials is a feature being implemented in all the Google auth client libraries to run on servers and to make using 2LO and service accounts easier and more secure.

The basic idea is to expose a single static function with no arguments that gets a credential that can represent the code based on the content. In Java this is named GoogleCredentials.getApplicationDefault, although the should blend fitting other names in the library while still fitting the feature name. It should do the following checks on the following order:
1. Check the environment variable GOOGLE_APPLICATION_CREDENTIALS for a credentials file.
2. Check a well known file location that could be supplied by a tool. (The Cloud SDK populates this file with developer credentials when you run "gcloud auth login".
3. If running on Google App Engine, use the GAE AppIdentity credentials.
4. If running on Google Compute Engine, use the GCE built-in credentials from the metadata server.

For steps (1) and (2), the file can be one of 2 JSON formats:
(A) User credentials with client id, client secret and refresh token populated from a previous 3LO flow.
(B) Service Account credentials using the JSON format supported by the Google Develoepers Console. This includes an email address and a PKCS#8 key so that it completely defines the account.

Other surface area needed:
1. A static method that takes either a file or a stream supporting the above formats. In Java this is named GoogleCredentials.fromStream(InputStream).
2. A way to create a clone of the credentials with specific scopes. This is needed by the GAE and and Service Account credentials, although it is best injected by API wrappers after the credential is created. In java, the instance methods createScopedRequired and createScoped provide this.

For referecne, the Java implementation is here:
https://code.google.com/p/google-api-java-client/source/browse/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/DefaultCredentialProvider.java
It also comprises the fromStream and getApplicationDefault overloads here:
https://code.google.com/p/google-api-java-client/source/browse/google-api-client/src/main/java/com/google/api/client/googleapis/auth/oauth2/GoogleCredential.java
For GAE support it also requires the component AppEngineCredentialWrapper here:
https://code.google.com/p/google-api-java-client/source/browse/google-api-client-appengine/src/main/java/com/google/api/client/googleapis/extensions/appengine/auth/oauth2/AppIdentityCredential.java

Most of the constituent building blocks are already present, so this is estimated to be about 5 days of work.

There are implementations happening in many other languages. Contact @anthmgoogle for more details.

**Comment by bradfitz** [comment]
What is 2LO?

**Comment by rakyll** [comment]
> What is 2LO?

Two-legged OAuth 2.0.

**Comment by adg** [comment]
Work in progress: https://go-review.googlesource.com/6074

(Not ready for review.)
