### ISSUE TITLE
enable providerAuthHeaderWorks configurable

### ISSUE THREAD

**Issue by HuKeping** [golang/oauth2#91]
hi there,
          Is it possible to make the providerAuthHeaderWorks  configurable? We like to use the golang/oauth2 project and don't want to break it so we can always get the newest version.
          For now, the provider list who's oauth2.0 flow are not standard was written as 
```
if strings.HasPrefix(tokenURL, "https://accounts.google.com/") ||
                strings.HasPrefix(tokenURL, "https://www.googleapis.com/") ||
                strings.HasPrefix(tokenURL, "https://github.com/") ||
                strings.HasPrefix(tokenURL, "https://api.instagram.com/") ||
                strings.HasPrefix(tokenURL, "https://www.douban.com/") ||
                strings.HasPrefix(tokenURL, "https://api.dropbox.com/") ||
                strings.HasPrefix(tokenURL, "https://api.soundcloud.com/") ||
                strings.HasPrefix(tokenURL, "https://www.linkedin.com/") ||
                strings.HasPrefix(tokenURL, "https://api.twitch.tv/") ||
                strings.HasPrefix(tokenURL, "https://connect.stripe.com/") {
                return false
}
```

We would break the git repo if we just put our url into it. 
I think many people may come across a similar issue

**Comment by adg** [comment]
We're not going to make it configurable, but if you know of other broken services you can [send us a change](https://github.com/golang/oauth2/blob/master/CONTRIBUTING.md) or file an issue.
