### ISSUE TITLE
Classic App Engine support

### ISSUE THREAD

**Issue by crhym3** [golang/oauth2#93]
https://github.com/golang/oauth2/commit/96e89befdc0f88d5868b297eb0e0727ce6978884 commit obviously broke my app.

> Users of classic App Engine must switch to using the new "google.golang.org/appengine" packages in order to use the oauth2 package.

What does this mean exactly? Is `google.golang.org/appengine` ready to be used on "classic" GAE apps? I've just took a quick look at the new package and [found this](https://github.com/golang/appengine/blob/06bbc86aa6edc69a04091ff99b696ebb4cbb2302/appengine.go#L22-L23): 

```go
func IsDevAppServer() bool {
	// TODO(dsymonds): Detect this.
	return false
}
```

I'm afraid there might be other such "todos". My app relies on funcs like `IsDevAppServer`.

**Comment by gmlewis** [comment]
I have not tried this out, but you should be able to do something like this:

```go
func IsDevAppServer() bool {
    return os.Getenv("RUN_WITH_DEVAPPSERVER") != ""
}
```

Alex, can you please try that out and see if it works for you?

**Comment by rakyll** [comment]
I think this bug needs to be opened against https://github.com/golang/appengine, Classic AppEngine (tm) gives us a promise of compatibility and therefore we merged 96e89be.

**Comment by dsymonds** [comment]
As far as I know, `IsDevAppServer` is the only piece that doesn't work transparently. @gmlewis's suggestion is probably right.

**Comment by rakyll** [comment]
Opened https://github.com/GoogleCloudPlatform/go-endpoints/pull/65.

**Comment by crhym3** [comment]
Thanks all. My point is if the original quote is true, I think it deserves more than just a commit message.

Here's where my app is now broken, it wasn't go-endpoints :)

```go
func serviceCredentials(c appengine.Context, scopes ...string) oauth2.TokenSource {
        cr := &jwt.Config{
                Email:      config.Google.ServiceAccount.Email,
                PrivateKey: []byte(config.Google.ServiceAccount.Key),
                Scopes:     scopes,
                TokenURL:   config.Google.TokenURL,
        }
        return cr.TokenSource(c), nil
}
```

`jwt.Config.TokenSource()` now accepts `context.Context`, so I'm trying to figure out how to make this work on a classic GAE app.

Any suggestions?

**Comment by crhym3** [comment]
Never mind. This seems to work now by replacing all `appengine/*` imports with `google.golang.org/appengine/*` and `appengine.Context` with `net/context.Context`.

I'm going to close this issue but I still think this deserves more than just a commit message. Maybe a blog post describing what's happening, pitfalls like `IsDevAppServer` and workarounds.

**Comment by adg** [comment]
On 7 March 2015 at 21:24, alex <notifications@github.com> wrote:

> I'm going to close this issue but I still think this deserves more than
> just a commit message. Maybe a blog post describing what's happening,
> pitfalls like IsDevAppServer and workarounds.
>

Thanks, that's a good suggestion. Sorry for the trouble, glad you worked it
out quickly.
