### ISSUE TITLE
client.Do not authenticating properly

### ISSUE THREAD

**Issue by rfrancis** [golang/oauth2#94]
I can't tell if this is a bug, a documentation gap, or just me being dumb, so I apologize if it turns out to be the last one, at least.

I'm writing code to authenticate via oauth2 with trakt.tv's API.  Let me first say that I have successfully done the same exchange and API call in Python using requests_oauthlib so I'm certain my details are correct, but I'm winding up with a 401 using golang.org/x/oauth2.  Here's my code after I've finished doing the exchange, including checking token.Valid() just to be sure:

    req,err := http.NewRequest("GET","https://api-v2launch.trakt.tv/users/rfrancis",nil)
    if(err!=nil) {
    fmt.Println(err)
    }   
    req.Header.Set("Content-Type","application/json")
    req.Header.Set("trakt-api-key",client_id)
    req.Header.Set("trakt-api-version","2")
 
    r,err := client.Do(req)

Long story short, err contains a 401, like so:

    &{401 Unauthorized 401 HTTP/1.1 1 1 map[Content-Type:[text/html] Cache-Control:[max-age=0, private, no-cache, no-store, must-revalidate] Date:[Mon, 09 Mar 2015 20:18:54 GMT] Vary:[Accept-Encoding] X-Content-Type-Options:[nosniff] X-Frame-O$tions:[SAMEORIGIN] Server:[cloudflare-nginx] Connection:[keep-alive] X-Xss-Prot$ction:[1; mode=block] Set-Cookie:[__cfduid=d0a639905c79e087aec441b26460c4b28142$932332; expires=Tue, 08-Mar-16 20:18:52 GMT; path=/; domain=.trakt.tv; HttpOnly$ X-Request-Id:[cc10e93d-188a-4753-aa95-1e65639542ac] X-Runtime:[0.350714] Cf-Ra$:[1c4978b7fad3042a-ORD]] 0xc2101fa0e0 -1 [chunked] false map[] 0xc2101d89c0}

So.... is Do a non-starter?  Is there a way I can set the headers while using Get if I have to use that?  What, in short, am I missing, or is there a real problem here? :)

Go version: go1.2.2 linux/amd64  (but I got the same results using 1.3.something on my Macbook Pro which I don't have handy at the moment, but whatever's current in homebrew)

Thanks.  I'm so close I can taste it...

**Comment by rakyll** [comment]
Where is your client is coming from? Could you send a snippet where you construct the client? Your request should surely contain an "Authorization" header if you're using the right client.

**Comment by rfrancis** [comment]
Sure thing:

    conf := &oauth2.Config {
        ClientID: client_id,
        ClientSecret: client_secret,
        Endpoint: oauth2.Endpoint {
            AuthURL: auth_url,
            TokenURL: token_url,
        },      
        RedirectURL: redirect_url,
    }   

    fmt.Println(conf.AuthCodeURL("gotrakt"))

    f := bufio.NewScanner(os.Stdin)
    f.Scan()
    code := f.Text()

    token,err := conf.Exchange(oauth2.NoContext,code)
    if(err!=nil) {
        fmt.Println(err)
    }   
    fmt.Println(token.Valid())
    client := conf.Client(oauth2.NoContext,token)

As I say, the various variables use above to construct the Config are the same as used in my working Python script, so I assume they're correct here (and no errors are generated and token.Valid() prints as true.)  So anyway it prints the URL, I paste it into the browser, copy and paste the code back into the Go program, and so forth.

**Comment by rakyll** [comment]
I can confirm that this is a bug, we've broken the (*Config).Client accessor, as we pass a nil token on https://github.com/golang/oauth2/blob/master/oauth2.go#L459. I am working on a fix.

**Comment by rfrancis** [comment]
Ah, okay!  It's just good to know I'm not crazy, at least in this respect.  Thanks so much for the quick followup!

**Comment by rakyll** [comment]
Mailed https://go-review.googlesource.com/#/c/7240/.

Apparently I was wrong, it reuses the existing token through the TokenSource and sets the Authorization header properly. Your server should be rejecting the response for some other reason.

Could you print the req2, right before it's been done [1]? It should contain an Authorization header in the form of "Bearer <access token>".

[1] https://github.com/golang/oauth2/blob/master/transport.go#L48

**Comment by rfrancis** [comment]
&{GET https://api-v2launch.trakt.tv/users/rfrancis HTTP/1.1 1 1
map[Content-Type:[application/json]
Trakt-Api-Key:[46eee1d00c5f2d4e9c19e736f82c7595ddcd92da1b2b5cc4e18f824a7f62ba2e]
Trakt-Api-Version:[2] Authorization:[bearer
632bf3d0663b0717daba486d9eb65a4f7b5c23c0b8c023066a2f8030f0fd1b16]] <nil> 0
[] false api-v2launch.trakt.tv map[] map[] <nil> map[]   <nil>}

**Comment by rakyll** [comment]
You have a valid Authorization header.

Your access token should be lacking permissions be valid for the action (missing scopes, etc), or your provider is rejecting you for some other authorization problems we can't help you with.

**Comment by rfrancis** [comment]
Absolutely bizarre.  Maybe the python library is adding some scope by
default or something.  Well, thanks, even though I'm still baffled. :)

**Comment by rakyll** [comment]
Please reopen and update this issue if you come across another problem related to the oauth2 package.
