### ISSUE TITLE
ConfigFromJSON only supports ClientIDs of type web.

### ISSUE THREAD

**Issue by kroikie** [golang/oauth2#95]
It would be helpful to allow the user to set the type of ClientID they have, when constructing a config from JSON, since the parent element is not always "web".

Could update constructor:
ConfigFromJSON(type string, jsonKey []byte, scope ...string) (*oauth2.Config, error)

Also include type enum for ClientID types.

**Comment by rakyll** [comment]
https://go-review.googlesource.com/#/c/7250/ resolved this issue.
