### ISSUE TITLE
basic auth in header breaks TrainingPeaks auth flow

### ISSUE THREAD

**Issue by cnbuff410** [golang/oauth2#97]
TrainingPeaks auth server doesn't allow "authorization" field to show up in the header. So the solution would be adding both

"https://oauth.sandbox.trainingpeaks.com/",
"https://oauth.trainingpeaks.com/",

into "brokenAuthHeaderProviders"

**Comment by cnbuff410** [comment]
https://go-review.googlesource.com/7450

My first time doing gerrit thing, not sure if it looks okay

**Comment by adg** [comment]
As the comment in `oauth2.go` says:

        // We will _not_ be adding configurable hooks
        // to this package to let users select server bugs.
