### ISSUE TITLE
Automatic configuration of oauth client transport for appengine?

### ISSUE THREAD

**Issue by perezd** [golang/oauth2#98]
In order to make this library work within appengine, I must write the following code:

```
func cloudContext(aeCtx context.Context) (context.Context, error) {
        conf, err := google.JWTConfigFromJSON(json, storage.ScopeFullControl)
        if err != nil {
                return nil, err
        }
        client := conf.Client(aeCtx)
        client.Transport = &oauth2.Transport{
                Source: google.AppEngineTokenSource(aeCtx, storage.ScopeFullControl),
                Base:   &urlfetch.Transport{Context: aeCtx},
        }
        return cloud.NewContext(projectId, client), nil
}
```

Would it be possible for this library to auto-detect its running in an appengine context and configure the client transport automatically?

**Comment by adg** [comment]
Yes, see #90

**Comment by perezd** [comment]
Cool thanks. Does this also address the urlfetch/roundtripper requirements
for GAE as well? I don't really see that in scope for #90.

**Comment by rakyll** [comment]
There is a separate bug with jwt.Config not being able to find out the right base RoundTripper on AppEngine. Reopening the issue.

**Comment by rakyll** [comment]
@gmlewis, would you like to give this one a look if you have time?

**Comment by gmlewis** [comment]
Yes, I'll look into it.

**Comment by gmlewis** [comment]
After investigating this, it seems to me like a better solution would be to put this wrapper into the `google.golang.org/cloud` package, as that is the only package that will benefit from it.  In other words, if someone is not using the `cloud` package, this wrapper will be of no use to them.

Something like this:

```go
func AppEngineTransport(aeCtx context.Context, projectID, jsonData string, scope ...string) (context.Context, error) {
        conf, err := google.JWTConfigFromJSON(jsonData, scope...)
        if err != nil {
                return nil, fmt.Errorf("cloud: unable to configure JWT from JSON: %v", err)
        }
        client := conf.Client(aeCtx)
        client.Transport = &oauth2.Transport{
                Source: google.AppEngineTokenSource(aeCtx, scope...),
                Base:   &urlfetch.Transport{Context: aeCtx},
        }
        return NewContext(projectID, client), nil
}
```

@okdave - what do you think?

**Comment by okdave** [comment]
I am a little confused exactly where the bug is now. From my understanding the following should do exactly what the OP needed:

    import (
        "appengine"
        "golang.org/x/oauth2/google"
    )
    <snip/>
    c := appengine.NewContext(r)
    client, err := google.DefaultClient(c, scope1, scope2)

The returned `client` can now be used directly with `cloud.NewContext`. Is that not working?

**Comment by gmlewis** [comment]
Ah, I see.  Finding the right RoundTripper on App Engine may still be an issue.
Let me delete my last comment since it will only cause more confusion.
Then I'll see if I can duplicate the RoundTripper problem.

**Comment by rakyll** [comment]
@gmlewis, are you looking at this issue or do you need help?

**Comment by gmlewis** [comment]
Sorry, this fell by the wayside.  I have not yet duplicated the RoundTripper problem.

**Comment by bradfitz** [comment]
I'm pretty sure this bug is both fixed (with Application Default Credentials work) and obsolete (by App Engine 1.11+ changes in gen2 runtimes).
