### ISSUE TITLE
 google.AppEngineTokenSource: appengine.Context does not implement context.Context

### ISSUE THREAD

**Issue by ukai** [golang/oauth2#99]
google.AppEngineTokenSource says "The provided context must have come from appengine.NewContext.", but appengine.Context (on appengine, not appenginevm) does not implement context.Context.

package t

import (
      "net/http"
      "appengine"
      "golang.org/x/oauth2/google"
)

func handle(w http.ResponseWriter, req *http.Request) {
  ctx := appengine.NewContext(req)
  _ = google.AppEngineTokenSource(ctx, "https://www.googleapis.com/auth/devstorage.read_only")
}

% goapp build .
./a.go:11: cannot use ctx (type "appengine".Context) as type context.Context in argument to google.AppEngineTokenSource:
        "appengine".Context does not implement context.Context (missing Deadline method)

% goapp version
go version go1.4.1 (appengine-1.9.18) linux/amd64

golang.org/x/oauth2 commit 42633ef623fcdbfd1a06e764610400f1d13c09f9

**Comment by ukai** [comment]
ah, should we use google.golang.org/appengine even on classic appengine?

**Comment by ukai** [comment]
need to update README of google.golang.org/appengine?
It sounds it is only for Managed VM.

**Comment by rakyll** [comment]
Yes, classic AppEngine (tm) supports importing from google.golang.org/appengine now. We discontinued support for "appengine" imports last week.

**Comment by ukai** [comment]
got it. thanks!
